In [1]:
####Visualizations
#### Importing dependencies 
import numpy as np
import pandas as pa
import seaborn as se
import matplotlib.pyplot as plt
from IPython.display import HTML

In [2]:
ball_by_ball=pa.read_csv("./train/train/ball_by_ball_data.csv")
match_data=pa.read_csv("./train/train/match_data.csv")
city_graph=match_data.groupby(['city'])['city'].count()
city_graph=pa.DataFrame(city_graph)
city_graph=match_data['city'].value_counts()
city_graph=pa.DataFrame(city_graph.reset_index())
city_graph.columns=['city','count']
city_graph.head(10)

         city  count
0      Mumbai     85
1   Bangalore     66
2     Kolkata     61
3       Delhi     60
4   Hyderabad     49
5     Chennai     48
6  Chandigarh     46
7      Jaipur     33
8        Pune     32
9      Durban     15

In [3]:
import plotly as pl

In [4]:
pl.__version__

'2.5.1'

In [5]:
import plotly.plotly as py
import plotly.graph_objs as go

In [6]:
import plotly

In [7]:
plotly.__version__

'2.5.1'

In [8]:
### Configuring Plotly Online 

plotly.tools.set_credentials_file(username="venuchalla",api_key='BtUDYmMmMDRxQcKBwMok')

In [9]:
plotly.__version__

'2.5.1'

In [10]:
### To work with plotly graphs offline import the following modules 
### When the graph command is written in the commandline the graph will be generated in the web browser.


from plotly.offline import download_plotlyjs,init_notebook_mode, plot, iplot

In [11]:
### to generate the graph offline with in jupyter 

init_notebook_mode(connected=True)

In [12]:
### Before generating the graphs in the ipython notebook use plotly.offline this will inject the plotly.js in the source files


import plotly
from plotly.graph_objs import Bar,Layout

In [13]:
"""plotly.offline.iplot()-----> is a function 
argument to this should be the JSON object {}


here plotly.offline.iplot()---> embeds the interative graph in the inline formate means in ipython notebook itself

&

plotly.offline.plot() ---> Prints the graphs in the external files as a HTML page.

"""

x= city_graph['city']
y=city_graph['count']

plotly.offline.iplot({
    "data": [Bar(x=x,y=y,marker=dict(color="rgba(50, 171, 96, 0.5)") )],
    "layout" : Layout(title="Number of matches played in each City since 2008", yaxis={"title":"No of Matches"})
})

In [14]:
match_data[['umpire1','umpire2']].head(10)

     umpire1         umpire2
0  Asad Rauf     RE Koertzen
1  MR Benson      SL Shastri
2  Aleem Dar  GA Pratapkumar
3   SJ Davis       DJ Harper
4  BF Bowden     K Hariharan
5  Aleem Dar       RB Tiffin
6  IL Howell       AM Saheba
7  DJ Harper  GA Pratapkumar
8  Asad Rauf       MR Benson
9  Aleem Dar       AM Saheba

In [15]:
umpires = [list(match_data['umpire1']),list(match_data['umpire2'])]

#### making list of list to a single list.

umpires=pa.Series(sum(umpires,[])).value_counts()
umpires=umpires.reset_index()
umpires.columns=['names','count']
top5_umpires=umpires.head(5)

In [16]:
#### Ploting the top 5 umpires standing in the IPL since 2008 to 2017

plotly.offline.iplot({
    "data": [Bar(x=top5_umpires['names'],y=top5_umpires['count'],marker=dict(color="rgb(158,202,225)"), opacity=0.5)],
    "layout": Layout(title="Top 5 umpires in IPL based on number matches they stood",yaxis={"title":"Number of matches"})
})

In [19]:
match_wins = match_data['winner']

match_wins=pa.DataFrame(match_wins.value_counts())
match_wins=match_wins.reset_index()
match_wins.columns=['teams','wins']

In [20]:
match_wins

   teams  wins
0     MI    92
1    CSK    79
2    KKR    77
3    RCB    73
4    KXI    70
5     RR    63
6     DD    62
7    SRH    42
8     DC    29
9    RPS    15
10    GL    13
11    PW    12
12   KTK     6

In [21]:
total_matchs_played=pa.Series(sum([list(match_data['team1_id']),list(match_data['team2_id'])],[]))

total_matchs_played=(pa.DataFrame(total_matchs_played.value_counts())).reset_index()
total_matchs_played.columns=['teams','matchs']
total_matchs_played=total_matchs_played.merge(match_wins, on="teams")
total_matchs_played['wining_percent']=(np.round((total_matchs_played['wins']/total_matchs_played['matchs'])*100,2)).apply(str)+"% Winning"

In [22]:
total_matchs_played

   teams  matchs  wins  wining_percent
0     MI     157    92   58.6% Winning
1    RCB     152    73  48.03% Winning
2    KKR     148    77  52.03% Winning
3    KXI     148    70   47.3% Winning
4     DD     147    62  42.18% Winning
5    CSK     131    79  60.31% Winning
6     RR     118    63  53.39% Winning
7    SRH      76    42  55.26% Winning
8     DC      75    29  38.67% Winning
9     PW      46    12  26.09% Winning
10   RPS      30    15   50.0% Winning
11    GL      30    13  43.33% Winning
12   KTK      14     6  42.86% Winning

In [23]:
### This is the grouped bar chart based on number of matches played and number of matchs won over since 2008

#### Trace 0 Bars ---> number of matches played
trace0 = Bar(
x=total_matchs_played['teams'], y=total_matchs_played['matchs'], name="Total matches Played", marker=dict(color="rgba(55, 83, 109,0.5)",),
)

#### Trace 1 Bars ---> number of matches Won
trace1 = Bar(
x=total_matchs_played['teams'],y=total_matchs_played['wins'], name ="Total matches Won", marker=dict(color="rgba(26, 118, 255,0.5)"),
text=total_matchs_played['wining_percent']   
)


data= [trace0,trace1]
#### Designing layout means axis,legends styles are done in this object  


layout = Layout(
title="Number of Matches played VS Matches Won",
xaxis = dict(
    tickfont = dict(
        size=14,
        color="rgb(107, 107, 107)"
    )),
yaxis =dict(
    title="Number of matches",
    tickfont = dict(
        size = 15,
        color = "rgb(107,107,107)"
    )
),

)
plotly.offline.iplot({
    "data":data,
    "layout":layout
})

The graphs shows that even though the number of matches played by CSK is less the winner percentage is high.

In [24]:
ball_by_ball.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,batsman_id,non_striker,non_striker_id,bowler,bowler_id,batsman_runs,extra_runs,player_dismissed,player_dismissed_id,dismissal_kind,is_super_over
0,2017_1,1,SRH,RCB,1,1,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
1,2017_1,1,SRH,RCB,1,2,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
2,2017_1,1,SRH,RCB,1,3,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,4,0,NaN,NaN,NaN,0
3,2017_1,1,SRH,RCB,1,4,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
4,2017_1,1,SRH,RCB,1,5,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,2,NaN,NaN,NaN,0

In [25]:
batsman_details=ball_by_ball[['match_id','inning','batting_team','batsman','batsman_runs']]
batsman_details=batsman_details.merge(match_data[['match_id','season']],on="match_id")

In [26]:
batsman_details.head()

  match_id  inning batting_team       batsman  batsman_runs  season
0   2017_1       1          SRH  David Warner             0    2017
1   2017_1       1          SRH  David Warner             0    2017
2   2017_1       1          SRH  David Warner             4    2017
3   2017_1       1          SRH  David Warner             0    2017
4   2017_1       1          SRH  David Warner             0    2017

In [27]:
batsman_runs=batsman_details.groupby(['match_id','season','inning','batting_team','batsman'])['batsman_runs'].agg({'balls_played':'count','batsman_runs':'sum'}).reset_index()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:

using a dict on a Series for aggregation
is deprecated and will be removed in a future version

In [28]:
#### Calculate the strike rate for every season than every match


batsman_runs_season=batsman_runs.groupby(['batsman'])['balls_played','batsman_runs'].agg({'balls_played':'sum','batsman_runs':'sum'}).reset_index()

In [29]:
batsman_runs_season['strick_rate']=np.round(batsman_runs_season['batsman_runs']/batsman_runs_season['balls_played']*100,2)

In [30]:
batsman_runs_season.head(10)

                 batsman  balls_played  batsman_runs  strick_rate
0         AB De Villiers          2402          3486       145.13
1          Aakash Chopra            75            53        70.67
2            Aaron Finch          1270          1604       126.30
3           Abdur Razzak             2             0         0.00
4       Abhimanyu Mithun            26            34       130.77
5         Abhinav Mukund            23            19        82.61
6  Abhishek Jhunjhunwala           218           217        99.54
7         Abhishek Nayar           588           672       114.29
8          Abhishek Raut           172           194       112.79
9             Abu Nechim            27            36       133.33

In [31]:
#### Ploting a scatter plot for the number of runs scored vs strike rate of the batsmen
from plotly.graph_objs import Scatter

trace0 = Scatter(x=batsman_runs_season['batsman_runs'],
                 y=batsman_runs_season['strick_rate'],
                 mode='markers',
                 marker=dict(size=9, color='rgba(152, 0, 0, .8)', line=dict(width=1)),
                 text=batsman_runs_season['batsman']
                 )
layout=Layout(title='Batsman Strick rate VS total run Scored',
              xaxis=dict(title="Total runs scored"),
              yaxis=dict(title="Over all Strick Rate"))


### Offline Scatter plot
### Thiz is JSON format

plotly.offline.iplot({
    "data":[trace0],
    "layout":layout
})

In [32]:
#### Over all bowler economy calculation..
#### coverting the overs to the actual decimals 

#### Formula: over_all_run_given/no_of_overs_bowled
#### preparing the data


bowler_details=ball_by_ball[['match_id','bowling_team','over','bowler','batsman_runs','extra_runs','player_dismissed','player_dismissed_id','dismissal_kind'
]]
bowler_details.head()

,match_id,bowling_team,over,bowler,batsman_runs,extra_runs,player_dismissed,player_dismissed_id,dismissal_kind
0,2017_1,RCB,1,Tymal Mills,0,0,NaN,NaN,NaN
1,2017_1,RCB,1,Tymal Mills,0,0,NaN,NaN,NaN
2,2017_1,RCB,1,Tymal Mills,4,0,NaN,NaN,NaN
3,2017_1,RCB,1,Tymal Mills,0,0,NaN,NaN,NaN
4,2017_1,RCB,1,Tymal Mills,0,2,NaN,NaN,NaN

In [33]:
bowler_overs=pa.DataFrame(bowler_details.groupby(['match_id','bowling_team','over','bowler'])['over','batsman_runs'].agg({"over":"count","batsman_runs":"sum"}))
bowler_overs.columns=['no_of_balls','runs_per_over']
bowler_overs=bowler_overs.reset_index()
bowler_overs['extras']=0

In [34]:
#### calculating the extras bowled per over

for i in range(len(bowler_overs)):
    if bowler_overs.iloc[i,4]>6:
        bowler_overs.iloc[i,6]=bowler_overs.iloc[i,4]-6
        bowler_overs.iloc[i,4]=6

In [35]:
bowler_overs=bowler_overs.groupby(['bowler'])['no_of_balls','runs_per_over','extras'].agg({'no_of_balls':"sum","runs_per_over":"sum","extras":"sum"}).reset_index()
bowler_overs.columns=['bowler','overs','run_given','total_extras']
bowler_overs['overs']=np.round(bowler_overs['overs']/6,1)

In [36]:
#### Calculation of economy for the bowlers 
#### formula: total_runs_given/overs_bowled


bowler_overs['economy']=np.round(bowler_overs['run_given']/bowler_overs['overs'],3)

In [37]:
bowler_overs.head()

                  bowler  overs  run_given  total_extras  economy
0            Aaron Finch    7.2         66             1    9.167
1        Aavishkar Salvi   25.0        190             6    7.600
2           Abdur Razzak    2.0         23             2   11.500
3       Abhimanyu Mithun   48.0        448            24    9.333
4  Abhishek Jhunjhunwala   14.2        126             3    8.873

In [38]:
####Wickets taken by the bowler if the dismissal kind is caught,bowled,lbw,hit wicket, stumped, caught and bowled
dismissal=['caught','bowled','lbw','hit wicket','stumped','caught and bowled']
wickets=bowler_details[bowler_details['dismissal_kind'].isin(dismissal)][['bowler','dismissal_kind']]
wickets=(wickets['bowler']).value_counts()
wickets=wickets.reset_index()
wickets.columns=['bowler','wickets']
print(wickets.head())
bowler_overs=bowler_overs.merge(wickets, on="bowler")
bowler_overs.head()

            bowler  wickets
0   Lasith Malinga      154
1      Amit Mishra      134
2  Harbhajan Singh      127
3    Piyush Chawla      126
4     Dwayne Bravo      122

                  bowler  overs  run_given  total_extras  economy  wickets
0            Aaron Finch    7.2         66             1    9.167        1
1        Aavishkar Salvi   25.0        190             6    7.600        7
2       Abhimanyu Mithun   48.0        448            24    9.333        7
3  Abhishek Jhunjhunwala   14.2        126             3    8.873        1
4         Abhishek Nayar   38.3        311             9    8.120        9

In [39]:
bowler_overs[(bowler_overs['economy']>4.0) & (bowler_overs['economy']<7.0)]

                   bowler  overs  run_given  total_extras  economy  wickets
11         Ajinkya Rahane    1.0          5             0    5.000        1
13          Ajit Chandila   39.0        242             0    6.205       11
16            Ali Murtaza   44.0        304             5    6.909        9
26             Andrew Tye   21.0        139             2    6.619       12
29            Anil Kumble  161.0       1027            17    6.379       45
40             Avesh Khan    4.0         23             0    5.750        1
43                B Kumar  330.3       2244            72    6.794      111
50             Ben Stokes   44.0        305            10    6.932       12
62       Charl Langeveldt   26.0        178             9    6.846       13
63         Chetanya Nanda    8.0         55             2    6.875        2
71             Dale Steyn  343.0       2209           101    6.440       92
73         Daniel Vettori  129.5        870             8    6.718       28
82    Dimitri Mascarenhas   51.3        353             2    6.881       19
84            Dirk Nannes  107.5        734            44    6.828       28
86       Dominic Thornely    7.0         38             2    5.429        3
88         Doug Bollinger   96.0        663            24    6.906       37
94          Fidel Edwards   23.7        144             8    6.076        5
95             G H Vihari    6.0         37             1    6.167        1
98          Glenn McGrath   54.0        352             5    6.519       12
99          Graham Napier    4.0         27             0    6.750        1
102       Harbhajan Singh  486.5       3295            70    6.773      127
111            J P Duminy  110.2        766            22    6.951       23
123          Jayant Yadav   30.0        193             3    6.433        4
129           Johan Botha  115.7        781            15    6.750       25
131         John Hastings    9.7         63             3    6.495        3
132           Justin Kemp    7.5         51             2    6.800        3
144         Krunal Pandya   71.2        492            13    6.910       16
148        Lasith Malinga  426.5       2766           135    6.485      154
150        Lee Carseldine    1.0          5             1    5.000        1
152       Lockie Ferguson   13.0         84             9    6.462        3
155         Makhaya Ntini   35.0        238             3    6.800        7
162        Michael Clarke   11.0         67             0    6.091        2
166        Mitchell Starc   96.7        656            32    6.784       34
168       Mohammad Hafeez   10.0         61             3    6.100        2
169         Mohammad Nabi   11.0         58             0    5.273        2
176         Murali Kartik  191.7       1341            32    6.995       31
179     Mustafizur Rahman   63.7        444            11    6.970       17
180  Muttiah Muralitharan  254.7       1642            53    6.447       64
184      Nuwan Kulasekara   17.0        115             5    6.765        5
192      Paul Collingwood   14.8        100             1    6.757        5
205          Rahul Sharma  154.7       1079             7    6.975       40
207         Rahul Tewatia   21.0        137             2    6.524        6
212           Rashid Khan   54.0        352             4    6.519       17
214          Ravi Rampaul   43.7        299            16    6.842       16
215   Ravichandran Ashwin  381.7       2409            69    6.311      100
219  Roelof van der Merwe   73.8        486            12    6.585       21
227    Ryan ten Doeschate   13.0         88             5    6.769        2
229           Sachin Baby    1.7          8             0    4.706        2
230  Sachithra Senanayake   32.0        206             3    6.438        9
240        Shahbaz Nadeem  186.0       1295            21    6.962       37
242       Shakib Al Hasan  153.5       1072            26    6.984       43
245         Shane Harwood   10.0         61             7    6.100        3
249         Shaun Pollock   46.0        297             4    6.457       11
258       Shrikant Mundhe    1.0          5             1    5.000        1
264         Sohail Tanvir   41.5        246            16    5.928       22
272          Sunil Narine  321.8       1999            25    6.212       95
279       Thilan Thushara   22.7        152             8    6.696        8
287       Tyron Henderson    6.0         40             0    6.667        1
299     Washington Sunder   30.0        183             2    6.100        8
300         Wayne Parnell   95.5        651            28    6.817       26

In [40]:
#### plotting the economy of the bowlers. So that during the acution.
#### Segregating the different colors' for very expensive, expensive, economical, very economical
#### Conditions:   very economical <7.0
####               economical >=7.0 and <=10.0
####               expensive >10.0 and <=12.0
####               very expensive >12.0 


Very_Economical = Scatter(x=bowler_overs[bowler_overs['economy']<7.0]['wickets'],
                 y=bowler_overs[bowler_overs['economy']<7.0]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(152, 0, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[bowler_overs['economy']<7.0]['bowler'],
                 name="Very_economical")

Economical = Scatter(x=bowler_overs[(bowler_overs['economy']>=7.0) & (bowler_overs['economy']<=10.0)]['wickets'],
                 y=bowler_overs[(bowler_overs['economy']>=7.0) & (bowler_overs['economy']<=10.0)]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(100, 255, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[(bowler_overs['economy']>=7.0) & (bowler_overs['economy']<=10.0)]['bowler'],
                 name="Economical")


Expensive = Scatter(x=bowler_overs[(bowler_overs['economy']>10.0) & (bowler_overs['economy']<=12.0)]['wickets'],
                 y=bowler_overs[(bowler_overs['economy']>10.0) & (bowler_overs['economy']<=12.0)]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(100, 100, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[(bowler_overs['economy']>10.0) & (bowler_overs['economy']<=12.0)]['bowler'],
                 name="Expensive")

Very_Expensive = Scatter(x=bowler_overs[bowler_overs['economy']>12.0]['wickets'],
                 y=bowler_overs[bowler_overs['economy']>12.0]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(255, 100, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[bowler_overs['economy']>12.0]['bowler'],
                 name="Very_expensive")

layout = Layout(title="Bowler Economy VS total wickets taken",
                xaxis=dict(title="Total wickets taken in series"),
                yaxis=dict(title="Over all Economy"))

plotly.offline.iplot({
    "data"  :[Very_Economical,Economical,Expensive,Very_Expensive],
    "layout":layout
})

In [41]:
matchs_played=(pa.Series(sum([list(match_data['team1_id']),list(match_data['team2_id'])],[]))).value_counts().reset_index()
matchs_played.columns=['team','matches']

#### Percentage of toss winning based on the matches since 2008.

toss_winners=(match_data['toss_winner'].value_counts()).reset_index()
toss_winners.columns=['team','toss_win_matches']
matchs_played=matchs_played.merge(toss_winners,on='team')
matchs_played['prcnt_toss_winning']= np.round(matchs_played['toss_win_matches']/matchs_played['matches']*100,2)
matchs_played['prcnt_toss_winning']=matchs_played['prcnt_toss_winning'].apply(str)+"% of Toss_winning"

In [42]:
matchs_played.head()

  team  matches  toss_win_matches      prcnt_toss_winning
0   MI      157                85  54.14% of Toss_winning
1  RCB      152                70  46.05% of Toss_winning
2  KKR      148                78   52.7% of Toss_winning
3  KXI      148                68  45.95% of Toss_winning
4   DD      147                72  48.98% of Toss_winning

In [43]:
#### Here we compared How many matches the team played overall and 
#### how many times they own the toss in terms of percentage it ploted.

Toss_winning= Bar(x=matchs_played['team'],
            y=matchs_played['toss_win_matches'],
            marker=dict(color="rgb(158,202,225)"),
            name='Toss_win',
            text=matchs_played['prcnt_toss_winning'])
Matches_played = Bar(x=matchs_played['team'],
             y=matchs_played['matches'],
             marker=dict(color='rgb(100,200,120)'),
             name='Matches_played')

layout = Layout(title="Matches Played VS Toss Winning",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of Matches"))

plotly.offline.iplot({
    "data":[Matches_played,Toss_winning],
    "layout":layout
})

In [44]:
#### What most of the toss winners are choosing the decision to feild or the bat.
#### Lets put a pie chart for the feild and bat decision.

toss_decision=pa.DataFrame((match_data['toss_decision'].value_counts()).reset_index())
toss_decision.columns=['decision','count']
#### appending the percentage for bat and feild.
toss_decision['percentage']=np.round(toss_decision['count']/sum(toss_decision['count'])*100,2)
toss_decision['percentage']=toss_decision['percentage'].apply(str)+"%"

from plotly.graph_objs import Pie

colors=['rgb(128, 0, 255)','rgb(255, 0, 128)']

decision = Pie(labels=toss_decision['decision'],
             values=toss_decision['count'],
             textinfo="label+value",
             marker=dict(colors=colors,
                         line = dict(width=2)),
             textfont=dict(size=20)
            )


plotly.offline.iplot({
    "data":[decision]
})

In [45]:
toss_decision

  decision  count percentage
0    field    363     57.08%
1      bat    273     42.92%

In [47]:
key_team=pa.read_csv("./train/train/key_teams.csv")
#### adding home cities..

cities={"MI":"Mumbai",
             "DD":"Delhi",
              "KKR":"Kolkata",
             "SRH":"Hyderabad",
            "CSK":"Chennai",
             "RR":"Jaipur",
            "RCB":"Bangalore",
            "KXI":"Chandigarh",
            "DC":"Hyderabad",
            "KTK":"Kochi",
            "RPS":"Pune",
           "GL":"Ahmedabad",
           "PW":"Pune"}

In [59]:
key_team['city']=[cities.get(row) for row in key_team['team_id']]

In [60]:
key_team

   team_id                    team_name        city
0       MI               Mumbai Indians      Mumbai
1       DD             Delhi Daredevils       Delhi
2      KKR        Kolkata Knight Riders     Kolkata
3      SRH          Sunrisers Hyderabad   Hyderabad
4      CSK          Chennai Super Kings     Chennai
5       RR             Rajasthan Royals      Jaipur
6      RCB  Royal Challengers Bangalore   Bangalore
7      KXI              Kings XI Punjab  Chandigarh
8       DC              Deccan Chargers   Hyderabad
9      KTK         Kochi Tuskers Kerala       Kochi
10     RPS      Rising Pune Supergiants        Pune
11      GL                Gujarat Lions   Ahmedabad
12      PW                Pune Warriors        Pune

In [53]:
home_ground_analysis=match_data[['team1_id','team2_id','winner','city']]

In [80]:
home_ground_analysis

,team1_id,team2_id,winner,city,home_grnd_team1,home_grnd_team2,winner_home_grnd
0,KKR,RCB,KKR,Bangalore,Kolkata,Bangalore,Kolkata
1,CSK,KXI,CSK,Chandigarh,Chennai,Chandigarh,Chennai
2,RR,DD,DD,Delhi,Jaipur,Delhi,Delhi
3,MI,RCB,RCB,Mumbai,Mumbai,Bangalore,Bangalore
4,DC,KKR,KKR,Kolkata,Hyderabad,Kolkata,Kolkata
5,KXI,RR,RR,Jaipur,Chandigarh,Jaipur,Jaipur
6,DC,DD,DD,Hyderabad,Hyderabad,Delhi,Delhi
7,CSK,MI,CSK,Chennai,Chennai,Mumbai,Chennai
8,DC,RR,RR,Hyderabad,Hyderabad,Jaipur,Jaipur
9,KXI,MI,KXI,Chandigarh,Chandigarh,Mumbai,Chandigarh
10,RCB,RR,RR,Bangalore,Bangalore,Jaipur,Jaipur
11,KKR,CSK,CSK,Chennai,Kolkata,Chennai,Chennai
12,MI,DC,DC,Mumbai,Mumbai,Hyderabad,Hyderabad
13,DD,KXI,KXI,Chandigarh,Delhi,Chandigarh,Chandigarh
14,CSK,RCB,CSK,Bangalore,Chennai,Bangalore,Chennai
15,KKR,MI,MI,Kolkata,Kolkata,Mumbai,Mumbai
16,DD,RCB,DD,Delhi,Delhi,Bangalore,Delhi
17,DC,KXI,KXI,Hyderabad,Hyderabad,Chandigarh,Chandigarh
18,RR,KKR,RR,Jaipur,Jaipur,Kolkata,Jaipur
19,CSK,DD,DD,Chennai,Chennai,Delhi,Delhi
20,DC,RCB,RCB,Hyderabad,Hyderabad,Bangalore,Bangalore
21,KXI,KKR,KXI,Chandigarh,Chandigarh,Kolkata,Chandigarh
22,MI,DD,MI,Mumbai,Mumbai,Delhi,Mumbai
23,CSK,RR,RR,Jaipur,Chennai,Jaipur,Jaipur
24,RCB,KXI,KXI,Bangalore,Bangalore,Chandigarh,Chandigarh
25,CSK,DC,DC,Chennai,Chennai,Hyderabad,Hyderabad
26,RR,MI,MI,Mumbai,Jaipur,Mumbai,Mumbai
27,DD,CSK,CSK,Delhi,Delhi,Chennai,Chennai
28,KKR,RCB,KKR,Kolkata,Kolkata,Bangalore,Kolkata
29,DC,RR,RR,Jaipur,Hyderabad,Jaipur,Jaipur
...,...,...,...,...,...,...,...
606,RCB,GL,GL,Bangalore,Bangalore,Ahmedabad,Ahmedabad
607,DD,KKR,KKR,Kolkata,Delhi,Kolkata,Kolkata
608,SRH,KXI,SRH,Chandigarh,Hyderabad,Chandigarh,Hyderabad
609,RPS,RCB,RPS,Pune,Pune,Bangalore,Pune
610,GL,MI,MI,Rajkot,Ahmedabad,Mumbai,Mumbai
611,DD,KXI,KXI,Chandigarh,Delhi,Chandigarh,Chandigarh
612,SRH,KKR,SRH,Hyderabad,Hyderabad,Kolkata,Hyderabad
613,RCB,MI,MI,Mumbai,Bangalore,Mumbai,Mumbai
614,GL,RPS,RPS,Pune,Ahmedabad,Pune,Pune
615,SRH,DD,DD,Delhi,Hyderabad,Delhi,Delhi
616,KKR,RPS,RPS,Kolkata,Kolkata,Pune,Pune
617,GL,DD,DD,Delhi,Ahmedabad,Delhi,Delhi
618,KXI,RCB,KXI,Bangalore,Chandigarh,Bangalore,Chandigarh
619,RPS,SRH,RPS,Hyderabad,Pune,Hyderabad,Pune
620,MI,DD,MI,Delhi,Mumbai,Delhi,Mumbai
621,RCB,KKR,KKR,Bangalore,Bangalore,Kolkata,Kolkata
622,KXI,GL,GL,Chandigarh,Chandigarh,Ahmedabad,Ahmedabad
623,MI,SRH,SRH,Hyderabad,Mumbai,Hyderabad,Hyderabad
624,KXI,KKR,KXI,Chandigarh,Chandigarh,Kolkata,Chandigarh
625,GL,DD,DD,Kanpur,Ahmedabad,Delhi,Delhi
626,KXI,MI,KXI,Mumbai,Chandigarh,Mumbai,Chandigarh
627,DD,RPS,DD,Delhi,Delhi,Pune,Delhi
628,GL,SRH,SRH,Kanpur,Ahmedabad,Hyderabad,Hyderabad
629,MI,KKR,MI,Kolkata,Mumbai,Kolkata,Mumbai
630,KXI,RPS,RPS,Pune,Chandigarh,Pune,Pune
631,RCB,DD,RCB,Delhi,Bangalore,Delhi,Bangalore
632,RPS,MI,RPS,Mumbai,Pune,Mumbai,Pune
633,SRH,KKR,KKR,Bangalore,Hyderabad,Kolkata,Kolkata
634,KKR,MI,MI,Bangalore,Kolkata,Mumbai,Mumbai
635,MI,RPS,MI,Hyderabad,Mumbai,Pune,Mumbai

In [58]:
home_ground_analysis['home_grnd_team1']=[cities.get(row) for row in home_ground_analysis['team1_id']]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [62]:
home_ground_analysis['home_grnd_team2']=[cities.get(row) for row in home_ground_analysis['team2_id']]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [79]:
home_ground_analysis['winner_home_grnd']=[cities.get(row) for row in home_ground_analysis['winner']]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [72]:
home_ground_analysis['winner_home_grnd']="NaN"

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [84]:
home_ground_analysis['home_grnd']=(home_ground_analysis['winner_home_grnd']==home_ground_analysis['city']).apply(int)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [96]:
homegrnd_pivot=home_ground_analysis.groupby(['winner','home_grnd'], as_index=False)['home_grnd'].agg({'count':'count'})

In [113]:
####Plotting the analysis of homeground....


trace0 = Bar(x=homegrnd_pivot[homegrnd_pivot['home_grnd']==0]['winner'],
             y=homegrnd_pivot[homegrnd_pivot['home_grnd']==0]['count'],
             marker=dict(color='rgba(100,200,240,0.5)',
                         line=dict(width=2,color='rgba(10,150,150,0.5)')),
             name="Non home ground"
            )

trace1 =Bar(x=homegrnd_pivot[homegrnd_pivot['home_grnd']==1]['winner'],
            y=homegrnd_pivot[homegrnd_pivot['home_grnd']==1]['count'],
            marker=dict(color='rgba(200,202,225,0.9)',
                        line= dict(width=2, color='rgba(100,160,200,0.5)')),
            name="home ground"
           )

layout = Layout(title="Match winnings in Home ground VS Non home ground",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of matches"))

plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})

In [116]:
#### Toss winner choosing the bat or feild decision VS his winning.


toss_winning=match_data[['toss_winner','toss_decision','winner']]

In [120]:
toss_winning['win']= pa.Series((toss_winning['toss_winner']==toss_winning['winner']).apply(int))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [130]:
toss_winning=toss_winning.groupby(['toss_winner','toss_decision','win'], as_index=False)['win'].agg({'count':'count'})

In [135]:
trace0 = Bar(x=toss_winning[toss_winning['toss_decision']=='field']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='field') & (toss_winning['win']==1)]['count'],
             marker=dict(color='rgb(180,150,200)'),
             name="Field"
            )

trace1 = Bar(x=toss_winning[toss_winning['toss_decision']=='bat']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='bat') & (toss_winning['win']==1)]['count'],
             marker=dict(color='rgb(180,150,100)'),
             name="Bat"
            )
layout = Layout(title="Winning of Toss and winning match VS field or bat",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of matchs Won"))

plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})

In [136]:
trace0 = Bar(x=toss_winning[toss_winning['toss_decision']=='field']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='field') & (toss_winning['win']==0)]['count'],
             marker=dict(color='rgb(180,150,200)'),
             name="Field"
            )

trace1 = Bar(x=toss_winning[toss_winning['toss_decision']=='bat']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='bat') & (toss_winning['win']==0)]['count'],
             marker=dict(color='rgb(180,150,100)'),
             name="Bat"
            )
layout = Layout(title="Winning of Toss and winning match VS field or bat",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of matchs Won"))

plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})