In [1]:
####Visualizations
#### Importing dependencies 
import numpy as np
import pandas as pa
import seaborn as se
import matplotlib.pyplot as plt
from IPython.display import HTML

In [31]:
ball_by_ball = pa.read_csv("./train/train/ball_by_ball_data.csv")
match_data = pa.read_csv("./train/train/match_data.csv")
player_roster = pa.read_csv("./train/train/player_rosters.csv")
key_teams = pa.read_csv("./train/train/key_teams.csv")
matchs_2018=pa.read_csv("./test/test/matches_2018.csv")
player_prediction_2018=pa.read_csv("./test/test/player_predictions.csv")

In [32]:
filter_data=ball_by_ball[['match_id','inning','batting_team','bowling_team','over','ball','bowler','bowler_id','batsman_runs','extra_runs','dismissal_kind']]
filter_data=filter_data.merge(match_data[['match_id','venue_id','season']],on='match_id')

In [33]:
players_2018=player_roster[player_roster['Season']==2018][['player_id','Player','Team']].reset_index()
del players_2018['index']
print(players_2018.head(10))

   player_id                Player Team
0          1  Mahendra Singh Dhoni  CSK
1          3   Ravichandran Ashwin  KXI
2         12         Parthiv Patel  RCB
3         24          Suresh Raina  CSK
4         30          Rohit Sharma   MI
5         47        AB De Villiers  RCB
6         52           Amit Mishra   DD
7         55          Manoj Tiwary  KXI
8         57        Shikhar Dhawan  SRH
9         58        Gautam Gambhir   DD

In [35]:
#### Replacing Team DC with SRH.

team_change={'DC':'SRH'}


filter_data=filter_data.replace({'batting_team':team_change,'bowling_team':team_change})

In [36]:
#### I want only the bowlers in 2018.

filter_data_2018=filter_data[filter_data['bowler_id'].isin(list(players_2018['player_id']))]

In [37]:
filter_data_2018['total_run_given']=filter_data_2018['batsman_runs']+filter_data_2018['extra_runs']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
filter_data_2018

,match_id,inning,batting_team,bowling_team,over,ball,bowler,bowler_id,batsman_runs,extra_runs,dismissal_kind,venue_id,season,total_run_given
7,2017_1,1,SRH,RCB,2,1,Aniket Choudhary,480,1,0,NaN,4,2017,1
8,2017_1,1,SRH,RCB,2,2,Aniket Choudhary,480,4,0,NaN,4,2017,4
9,2017_1,1,SRH,RCB,2,3,Aniket Choudhary,480,0,1,NaN,4,2017,1
10,2017_1,1,SRH,RCB,2,4,Aniket Choudhary,480,6,0,NaN,4,2017,6
11,2017_1,1,SRH,RCB,2,5,Aniket Choudhary,480,0,0,caught,4,2017,0
12,2017_1,1,SRH,RCB,2,6,Aniket Choudhary,480,0,0,NaN,4,2017,0
13,2017_1,1,SRH,RCB,2,7,Aniket Choudhary,480,4,0,NaN,4,2017,4
20,2017_1,1,SRH,RCB,4,1,Yuzvendra Chahal,682,0,0,NaN,4,2017,0
21,2017_1,1,SRH,RCB,4,2,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
22,2017_1,1,SRH,RCB,4,3,Yuzvendra Chahal,682,0,0,NaN,4,2017,0
23,2017_1,1,SRH,RCB,4,4,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
24,2017_1,1,SRH,RCB,4,5,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
25,2017_1,1,SRH,RCB,4,6,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
32,2017_1,1,SRH,RCB,6,1,Shane Watson,175,4,0,NaN,4,2017,4
33,2017_1,1,SRH,RCB,6,2,Shane Watson,175,4,0,NaN,4,2017,4
34,2017_1,1,SRH,RCB,6,3,Shane Watson,175,0,0,NaN,4,2017,0
35,2017_1,1,SRH,RCB,6,4,Shane Watson,175,4,0,NaN,4,2017,4
36,2017_1,1,SRH,RCB,6,5,Shane Watson,175,4,0,NaN,4,2017,4
37,2017_1,1,SRH,RCB,6,6,Shane Watson,175,1,0,NaN,4,2017,1
38,2017_1,1,SRH,RCB,7,1,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
39,2017_1,1,SRH,RCB,7,2,Yuzvendra Chahal,682,0,0,NaN,4,2017,0
40,2017_1,1,SRH,RCB,7,3,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
41,2017_1,1,SRH,RCB,7,4,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
42,2017_1,1,SRH,RCB,7,5,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
43,2017_1,1,SRH,RCB,7,6,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
50,2017_1,1,SRH,RCB,9,1,Yuzvendra Chahal,682,2,0,NaN,4,2017,2
51,2017_1,1,SRH,RCB,9,2,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
52,2017_1,1,SRH,RCB,9,3,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
53,2017_1,1,SRH,RCB,9,4,Yuzvendra Chahal,682,1,0,NaN,4,2017,1
54,2017_1,1,SRH,RCB,9,5,Yuzvendra Chahal,682,2,0,NaN,4,2017,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150430,2016_60,2,RCB,SRH,16,1,Ben Cutting,526,1,0,NaN,7,2016,1
150431,2016_60,2,RCB,SRH,16,2,Ben Cutting,526,1,0,NaN,7,2016,1
150432,2016_60,2,RCB,SRH,16,3,Ben Cutting,526,0,0,bowled,7,2016,0
150433,2016_60,2,RCB,SRH,16,4,Ben Cutting,526,0,0,NaN,7,2016,0
150434,2016_60,2,RCB,SRH,16,5,Ben Cutting,526,1,0,NaN,7,2016,1
150435,2016_60,2,RCB,SRH,16,6,Ben Cutting,526,1,0,NaN,7,2016,1
150436,2016_60,2,RCB,SRH,17,1,Mustafizur Rahman,593,0,0,NaN,7,2016,0
150437,2016_60,2,RCB,SRH,17,2,Mustafizur Rahman,593,2,0,NaN,7,2016,2
150438,2016_60,2,RCB,SRH,17,3,Mustafizur Rahman,593,0,0,caught,7,2016,0
150439,2016_60,2,RCB,SRH,17,4,Mustafizur Rahman,593,1,0,NaN,7,2016,1
150440,2016_60,2,RCB,SRH,17,5,Mustafizur Rahman,593,6,0,NaN,7,2016,6
150441,2016_60,2,RCB,SRH,17,6,Mustafizur Rahman,593,1,0,NaN,7,2016,1
150442,2016_60,2,RCB,SRH,18,1,B Kumar,691,0,0,NaN,7,2016,0
150443,2016_60,2,RCB,SRH,18,2,B Kumar,691,1,0,NaN,7,2016,1
150444,2016_60,2,RCB,SRH,18,3,B Kumar,691,1,0,NaN,7,2016,1
150445,2016_60,2,RCB,SRH,18,4,B Kumar,691,0,0,NaN,7,2016,0
150446,2016_60,2,RCB,SRH,18,5,B Kumar,691,0,1,NaN,7,2016,1
150447,2016_60,2,RCB,SRH,18,6,B Kumar,691,4,0,NaN,7,2016,4
150448,2016_60,2,RCB,SRH,19,1,Mustafizur Rahman,593,1,0,run out,7,2016,1
150449,2016_60,2,RCB,SRH,19,2,Mustafizur Rahman,593,2,0,NaN,7,2016,2
150450,2016_60,2,RCB,SRH,19,3,Mustafizur Rahman,593,0,0,NaN,7,2016,0
150451,2016_60,2,RCB,SRH,19,4,Mustafizur Rahman,593,0,1,NaN,7,2016,1
150452,2016_60,2,RCB,SRH,19,5,Mustafizur Rahman,593,2,0,NaN,7,2016,2
150453,2016_60,2,RCB,SRH,19,6,Mustafizur Rahman,593,6,0,NaN,7,2016,6
150454,2016_60,2,RCB,SRH,20,1,B Kumar,691,1,0,NaN,7,2016,1
150455,2016_60,2,RCB,SRH,20,2,B Kumar,691,2,0,NaN,7,2016,2
150456,2016_60,2,RCB,SRH,20,3,B Kumar,691,0,0,run out,7,2016,0
150457,2016_60,2,RCB,SRH,20,4,B Kumar,691,0,1,NaN,7,2016,1
150458,2016_60,2,RCB,SRH,20,5,B Kumar,691,1,0,NaN,7,2016,1
150459,2016_60,2,RCB,SRH,20,6,B Kumar,691,4,0,NaN,7,2016,4

In [9]:
#### seperating first and second innings.

filter_data_1st_inn = filter_data_2018[filter_data_2018['inning']==1]
filter_data_2nd_inn = filter_data_2018[filter_data_2018['inning']==2]

############################################################################################################################

# First innings wickets

In [10]:
balls_runs_1st_inn=filter_data_1st_inn.groupby(['match_id','venue_id','batting_team','bowling_team','bowler_id'], as_index=False)['total_run_given'].agg({'total_run_given':'sum','ball_bowled':'count'})

In [14]:
dismissal_kind=['caught', 'bowled', 'lbw', 'caught and bowled','stumped', 'hit wicket']

In [18]:
wickets_1st_inn=filter_data_1st_inn[filter_data_1st_inn['dismissal_kind'].isin(dismissal_kind)]

In [19]:
wickets_1st_inn['dismissal_kind']=1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
wickets_1st_inn=wickets_1st_inn.groupby(['match_id','batting_team','bowling_team','bowler_id'],as_index=False)['dismissal_kind'].sum()

In [24]:
wickets_1st_inn

    match_id batting_team bowling_team  bowler_id  dismissal_kind
0    2008_10          KXI           MI        118               2
1    2008_10          KXI           MI        131               3
2    2008_11          RCB           RR        175               2
3    2008_14           DD          KXI         88               1
4    2008_16          KKR           MI        114               1
5    2008_18           DC          KXI        102               3
6    2008_21           DC          RCB        149               2
7    2008_21           DC          RCB        153               3
8    2008_23           MI           DD         63               1
9    2008_24          CSK           RR        175               1
10   2008_25          RCB          KXI        102               3
11   2008_27           RR           MI        114               2
12   2008_27           RR           MI        118               2
13   2008_30           DC           RR        171               1
14   2008_30           DC           RR        175               1
15   2008_32          CSK          KXI        102               1
16   2008_34           DD           RR        175               2
17   2008_35          RCB          KXI        102               2
18   2008_36          KKR           DD         63               1
19   2008_37          CSK           MI        114               2
20   2008_37          CSK           MI        118               3
21   2008_38          KXI           RR        171               1
22   2008_38          KXI           RR        175               1
23   2008_40          KKR           MI        114               2
24   2008_46          KKR           RR        171               1
25   2008_50           MI           DD         52               1
26   2008_51           RR          CSK         24               1
27   2008_56           RR           DD         52               2
28   2008_58          CSK           RR        171               3
29   2008_58          CSK           RR        175               1
..       ...          ...          ...        ...             ...
882  2017_52           GL          SRH         71               1
883  2017_52           GL          SRH        634               3
884  2017_52           GL          SRH        681               4
885  2017_52           GL          SRH        691               2
886  2017_53           MI          KKR        471               1
887  2017_53           MI          KKR        512               1
888  2017_53           MI          KKR        565               2
889  2017_54          KXI          RPS        341               2
890  2017_54          KXI          RPS        361               2
891  2017_54          KXI          RPS        518               3
892  2017_55          RCB           DD        351               1
893  2017_55          RCB           DD        514               2
894  2017_56          RPS           MI        254               1
895  2017_57          SRH          KKR        102               1
896  2017_57          SRH          KKR        208               2
897  2017_57          SRH          KKR        484               3
898  2017_57          SRH          KKR        565               1
899  2017_58          KKR           MI        254               4
900  2017_58          KKR           MI        487               3
901  2017_58          KKR           MI        655               2
902  2017_59           MI          RPS        341               2
903  2017_59           MI          RPS        361               2
904   2017_6           GL          SRH        634               3
905   2017_6           GL          SRH        691               2
906   2017_7          KKR           MI        487               1
907   2017_7          KKR           MI        582               3
908   2017_8          RCB          KXI        479               1
909   2017_8          RCB          KXI        485               1
910   2017_9           DD          RPS        412               1
911   2017_9           DD          RPS        507               1

[912 rows x 5 columns]

In [29]:
final_1st_inn_data=balls_runs_1st_inn.merge(wickets_1st_inn,on=['match_id','bowler_id','batting_team','bowling_team'])

In [41]:
final_1st_inn_data

,match_id,venue_id,batting_team,bowling_team,bowler_id,total_run_given,ball_bowled,dismissal_kind,average
0,2008_10,9,KXI,MI,118,38,26,2,0
1,2008_10,9,KXI,MI,131,33,25,3,0
2,2008_11,7,RCB,RR,175,20,25,2,0
3,2008_14,9,DD,KXI,88,11,13,1,0
4,2008_16,3,KKR,MI,114,25,25,1,0
5,2008_18,4,DC,KXI,102,28,24,3,0
6,2008_21,4,DC,RCB,149,25,24,2,0
7,2008_21,4,DC,RCB,153,27,25,3,0
8,2008_23,10,MI,DD,63,22,25,1,0
9,2008_24,6,CSK,RR,175,23,26,1,0
10,2008_25,7,RCB,KXI,102,25,25,3,0
11,2008_27,10,RR,MI,114,14,18,2,0
12,2008_27,10,RR,MI,118,21,18,2,0
13,2008_30,6,DC,RR,171,19,12,1,0
14,2008_30,6,DC,RR,175,23,19,1,0
15,2008_32,5,CSK,KXI,102,36,19,1,0
16,2008_34,6,DD,RR,175,24,24,2,0
17,2008_35,9,RCB,KXI,102,33,25,2,0
18,2008_36,3,KKR,DD,63,29,27,1,0
19,2008_37,1,CSK,MI,114,38,24,2,0
20,2008_37,1,CSK,MI,118,33,28,3,0
21,2008_38,9,KXI,RR,171,24,12,1,0
22,2008_38,9,KXI,RR,175,41,25,1,0
23,2008_40,1,KKR,MI,114,14,19,2,0
24,2008_46,3,KKR,RR,171,14,12,1,0
25,2008_50,2,MI,DD,52,23,24,1,0
26,2008_51,5,RR,CSK,24,20,12,1,0
27,2008_56,1,RR,DD,52,38,25,2,0
28,2008_58,10,CSK,RR,171,22,24,3,0
29,2008_58,10,CSK,RR,175,31,26,1,0
...,...,...,...,...,...,...,...,...,...
882,2017_52,34,GL,SRH,71,32,25,1,0
883,2017_52,34,GL,SRH,634,34,24,3,0
884,2017_52,34,GL,SRH,681,32,24,4,0
885,2017_52,34,GL,SRH,691,26,21,2,0
886,2017_53,3,MI,KKR,471,16,18,1,0
887,2017_53,3,MI,KKR,512,29,18,1,0
888,2017_53,3,MI,KKR,565,31,26,2,0
889,2017_54,32,KXI,RPS,341,10,12,2,0
890,2017_54,32,KXI,RPS,361,12,18,2,0
891,2017_54,32,KXI,RPS,518,19,26,3,0
892,2017_55,2,RCB,DD,351,12,13,1,0
893,2017_55,2,RCB,DD,514,22,26,2,0
894,2017_56,1,RPS,MI,254,30,24,1,0
895,2017_57,7,SRH,KKR,102,27,18,1,0
896,2017_57,7,SRH,KKR,208,21,25,2,0
897,2017_57,7,SRH,KKR,484,22,24,3,0
898,2017_57,7,SRH,KKR,565,31,25,1,0
899,2017_58,7,KKR,MI,254,17,25,4,0
900,2017_58,7,KKR,MI,487,7,18,3,0
901,2017_58,7,KKR,MI,655,28,26,2,0
902,2017_59,4,MI,RPS,341,35,26,2,0
903,2017_59,4,MI,RPS,361,21,24,2,0
904,2017_6,4,GL,SRH,634,19,24,3,0
905,2017_6,4,GL,SRH,691,23,24,2,0
906,2017_7,1,KKR,MI,487,39,26,1,0
907,2017_7,1,KKR,MI,582,24,24,3,0
908,2017_8,8,RCB,KXI,479,26,25,1,0
909,2017_8,8,RCB,KXI,485,12,24,1,0
910,2017_9,32,DD,RPS,412,36,20,1,0
911,2017_9,32,DD,RPS,507,25,25,1,0

In [40]:
### Averge of a bowler.
### formula:  Run_given/wickets_taken.
### lower the bowling average better the bowler is performing.

### Create Average variable.

final_1st_inn_data['average']=0