In [26]:
####Visualizations
#### Importing dependencies 
import numpy as np
import pandas as pa
import seaborn as se
import matplotlib.pyplot as plt
from IPython.display import HTML

In [27]:
ball_by_ball=pa.read_csv("./train/train/ball_by_ball_data.csv")
match_data=pa.read_csv("./train/train/match_data.csv")
city_graph=match_data.groupby(['city'])['city'].count()
city_graph=pa.DataFrame(city_graph)
city_graph=match_data['city'].value_counts()
city_graph=pa.DataFrame(city_graph.reset_index())
city_graph.columns=['city','count']
city_graph.head(10)

         city  count
0      Mumbai     85
1   Bangalore     66
2     Kolkata     61
3       Delhi     60
4   Hyderabad     49
5     Chennai     48
6  Chandigarh     46
7      Jaipur     33
8        Pune     32
9      Durban     15

In [28]:
import plotly as pl

In [29]:
pl.__version__

'2.5.1'

In [30]:
import plotly.plotly as py
import plotly.graph_objs as go

In [31]:
import plotly

In [32]:
plotly.__version__

'2.5.1'

In [33]:
### Configuring Plotly Online 

plotly.tools.set_credentials_file(username="venuchalla",api_key='BtUDYmMmMDRxQcKBwMok')

In [34]:
plotly.__version__

'2.5.1'

In [35]:
### To work with plotly graphs offline import the following modules 
### When the graph command is written in the commandline the graph will be generated in the web browser.


from plotly.offline import download_plotlyjs,init_notebook_mode, plot, iplot

In [36]:
### to generate the graph offline with in jupyter 

init_notebook_mode(connected=True)

In [37]:
### Before generating the graphs in the ipython notebook use plotly.offline this will inject the plotly.js in the source files


import plotly
from plotly.graph_objs import Bar,Layout

In [38]:
"""plotly.offline.iplot()-----> is a function 
argument to this should be the JSON object {}


here plotly.offline.iplot()---> embeds the interative graph in the inline formate means in ipython notebook itself

&

plotly.offline.plot() ---> Prints the graphs in the external files as a HTML page.

"""

x= city_graph['city']
y=city_graph['count']

plotly.offline.iplot({
    "data": [Bar(x=x,y=y,marker=dict(color="rgba(50, 171, 96, 0.5)") )],
    "layout" : Layout(title="Number of matches played in each City since 2008", yaxis={"title":"No of Matches"})
})

In [39]:
match_data[['umpire1','umpire2']].head(10)

     umpire1         umpire2
0  Asad Rauf     RE Koertzen
1  MR Benson      SL Shastri
2  Aleem Dar  GA Pratapkumar
3   SJ Davis       DJ Harper
4  BF Bowden     K Hariharan
5  Aleem Dar       RB Tiffin
6  IL Howell       AM Saheba
7  DJ Harper  GA Pratapkumar
8  Asad Rauf       MR Benson
9  Aleem Dar       AM Saheba

In [40]:
umpires = [list(match_data['umpire1']),list(match_data['umpire2'])]

#### making list of list to a single list.

umpires=pa.Series(sum(umpires,[])).value_counts()
umpires=umpires.reset_index()
umpires.columns=['names','count']
top5_umpires=umpires.head(5)

In [41]:
#### Ploting the top 5 umpires standing in the IPL since 2008 to 2017

plotly.offline.iplot({
    "data": [Bar(x=top5_umpires['names'],y=top5_umpires['count'],marker=dict(color="rgb(158,202,225)"), opacity=0.5)],
    "layout": Layout(title="Top 5 umpires in IPL based on number matches they stood",yaxis={"title":"Number of matches"})
})

In [42]:
match_wins = match_data['winner']

match_wins=pa.DataFrame(match_wins.value_counts())
match_wins=match_wins.reset_index()
match_wins.columns=['teams','wins']

In [43]:
match_wins

   teams  wins
0     MI    92
1    CSK    79
2    KKR    77
3    RCB    73
4    KXI    70
5     RR    63
6     DD    62
7    SRH    42
8     DC    29
9    RPS    15
10    GL    13
11    PW    12
12   KTK     6

In [44]:
total_matchs_played=pa.Series(sum([list(match_data['team1_id']),list(match_data['team2_id'])],[]))

total_matchs_played=(pa.DataFrame(total_matchs_played.value_counts())).reset_index()
total_matchs_played.columns=['teams','matchs']
total_matchs_played=total_matchs_played.merge(match_wins, on="teams")
total_matchs_played['wining_percent']=(np.round((total_matchs_played['wins']/total_matchs_played['matchs'])*100,2)).apply(str)+"% Winning"

In [45]:
total_matchs_played

   teams  matchs  wins  wining_percent
0     MI     157    92   58.6% Winning
1    RCB     152    73  48.03% Winning
2    KXI     148    70   47.3% Winning
3    KKR     148    77  52.03% Winning
4     DD     147    62  42.18% Winning
5    CSK     131    79  60.31% Winning
6     RR     118    63  53.39% Winning
7    SRH      76    42  55.26% Winning
8     DC      75    29  38.67% Winning
9     PW      46    12  26.09% Winning
10    GL      30    13  43.33% Winning
11   RPS      30    15   50.0% Winning
12   KTK      14     6  42.86% Winning

In [46]:
### This is the grouped bar chart based on number of matches played and number of matchs won over since 2008

#### Trace 0 Bars ---> number of matches played
trace0 = Bar(
x=total_matchs_played['teams'], y=total_matchs_played['matchs'], name="Total matches Played", marker=dict(color="rgba(55, 83, 109,0.5)",),
)

#### Trace 1 Bars ---> number of matches Won
trace1 = Bar(
x=total_matchs_played['teams'],y=total_matchs_played['wins'], name ="Total matches Won", marker=dict(color="rgba(26, 118, 255,0.5)"),
text=total_matchs_played['wining_percent']   
)


data= [trace0,trace1]
#### Designing layout means axis,legends styles are done in this object  


layout = Layout(
title="Number of Matches played VS Matches Won",
xaxis = dict(
    tickfont = dict(
        size=14,
        color="rgb(107, 107, 107)"
    )),
yaxis =dict(
    title="Number of matches",
    tickfont = dict(
        size = 15,
        color = "rgb(107,107,107)"
    )
),

)
plotly.offline.iplot({
    "data":data,
    "layout":layout
})

The graphs shows that even though the number of matches played by CSK is less the winner percentage is high.

In [47]:
ball_by_ball.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,batsman_id,non_striker,non_striker_id,bowler,bowler_id,batsman_runs,extra_runs,player_dismissed,player_dismissed_id,dismissal_kind,is_super_over
0,2017_1,1,SRH,RCB,1,1,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
1,2017_1,1,SRH,RCB,1,2,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
2,2017_1,1,SRH,RCB,1,3,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,4,0,NaN,NaN,NaN,0
3,2017_1,1,SRH,RCB,1,4,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
4,2017_1,1,SRH,RCB,1,5,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,2,NaN,NaN,NaN,0

In [48]:
batsman_details=ball_by_ball[['match_id','inning','batting_team','batsman','batsman_runs']]
batsman_details=batsman_details.merge(match_data[['match_id','season']],on="match_id")

In [49]:
batsman_details.head()

  match_id  inning batting_team       batsman  batsman_runs  season
0   2017_1       1          SRH  David Warner             0    2017
1   2017_1       1          SRH  David Warner             0    2017
2   2017_1       1          SRH  David Warner             4    2017
3   2017_1       1          SRH  David Warner             0    2017
4   2017_1       1          SRH  David Warner             0    2017

In [50]:
batsman_runs=batsman_details.groupby(['match_id','season','inning','batting_team','batsman'])['batsman_runs'].agg({'balls_played':'count','batsman_runs':'sum'}).reset_index()

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning:

using a dict on a Series for aggregation
is deprecated and will be removed in a future version

In [51]:
#### Calculate the strike rate for every season than every match


batsman_runs_season=batsman_runs.groupby(['batsman'])['balls_played','batsman_runs'].agg({'balls_played':'sum','batsman_runs':'sum'}).reset_index()

In [52]:
batsman_runs_season['strick_rate']=np.round(batsman_runs_season['batsman_runs']/batsman_runs_season['balls_played']*100,2)

In [53]:
batsman_runs_season.head(10)

                 batsman  balls_played  batsman_runs  strick_rate
0         AB De Villiers          2402          3486       145.13
1          Aakash Chopra            75            53        70.67
2            Aaron Finch          1270          1604       126.30
3           Abdur Razzak             2             0         0.00
4       Abhimanyu Mithun            26            34       130.77
5         Abhinav Mukund            23            19        82.61
6  Abhishek Jhunjhunwala           218           217        99.54
7         Abhishek Nayar           588           672       114.29
8          Abhishek Raut           172           194       112.79
9             Abu Nechim            27            36       133.33

In [54]:
#### Ploting a scatter plot for the number of runs scored vs strike rate of the batsmen
from plotly.graph_objs import Scatter

trace0 = Scatter(x=batsman_runs_season['batsman_runs'],
                 y=batsman_runs_season['strick_rate'],
                 mode='markers',
                 marker=dict(size=9, color='rgba(152, 0, 0, .8)', line=dict(width=1)),
                 text=batsman_runs_season['batsman']
                 )
layout=Layout(title='Batsman Strick rate VS total run Scored',
              xaxis=dict(title="Total runs scored"),
              yaxis=dict(title="Over all Strick Rate"))


### Offline Scatter plot
### Thiz is JSON format

plotly.offline.iplot({
    "data":[trace0],
    "layout":layout
})

In [55]:
#### Over all bowler economy calculation..
#### coverting the overs to the actual decimals 

#### Formula: over_all_run_given/no_of_overs_bowled
#### preparing the data


bowler_details=ball_by_ball[['match_id','bowling_team','over','bowler','batsman_runs','extra_runs','player_dismissed','player_dismissed_id','dismissal_kind'
]]
bowler_details.head()

,match_id,bowling_team,over,bowler,batsman_runs,extra_runs,player_dismissed,player_dismissed_id,dismissal_kind
0,2017_1,RCB,1,Tymal Mills,0,0,NaN,NaN,NaN
1,2017_1,RCB,1,Tymal Mills,0,0,NaN,NaN,NaN
2,2017_1,RCB,1,Tymal Mills,4,0,NaN,NaN,NaN
3,2017_1,RCB,1,Tymal Mills,0,0,NaN,NaN,NaN
4,2017_1,RCB,1,Tymal Mills,0,2,NaN,NaN,NaN

In [56]:
bowler_overs=pa.DataFrame(bowler_details.groupby(['match_id','bowling_team','over','bowler'])['over','batsman_runs'].agg({"over":"count","batsman_runs":"sum"}))
bowler_overs.columns=['no_of_balls','runs_per_over']
bowler_overs=bowler_overs.reset_index()
bowler_overs['extras']=0

In [57]:
#### calculating the extras bowled per over

for i in range(len(bowler_overs)):
    if bowler_overs.iloc[i,4]>6:
        bowler_overs.iloc[i,6]=bowler_overs.iloc[i,4]-6
        bowler_overs.iloc[i,4]=6

In [58]:
bowler_overs=bowler_overs.groupby(['bowler'])['no_of_balls','runs_per_over','extras'].agg({'no_of_balls':"sum","runs_per_over":"sum","extras":"sum"}).reset_index()
bowler_overs.columns=['bowler','overs','run_given','total_extras']
bowler_overs['overs']=np.round(bowler_overs['overs']/6,1)

In [59]:
#### Calculation of economy for the bowlers 
#### formula: total_runs_given/overs_bowled


bowler_overs['economy']=np.round(bowler_overs['run_given']/bowler_overs['overs'],3)

In [60]:
bowler_overs.head()

                  bowler  overs  run_given  total_extras  economy
0            Aaron Finch    7.2         66             1    9.167
1        Aavishkar Salvi   25.0        190             6    7.600
2           Abdur Razzak    2.0         23             2   11.500
3       Abhimanyu Mithun   48.0        448            24    9.333
4  Abhishek Jhunjhunwala   14.2        126             3    8.873

In [61]:
####Wickets taken by the bowler if the dismissal kind is caught,bowled,lbw,hit wicket, stumped, caught and bowled
dismissal=['caught','bowled','lbw','hit wicket','stumped','caught and bowled']
wickets=bowler_details[bowler_details['dismissal_kind'].isin(dismissal)][['bowler','dismissal_kind']]
wickets=(wickets['bowler']).value_counts()
wickets=wickets.reset_index()
wickets.columns=['bowler','wickets']
print(wickets.head())
bowler_overs=bowler_overs.merge(wickets, on="bowler")
bowler_overs.head()

            bowler  wickets
0   Lasith Malinga      154
1      Amit Mishra      134
2  Harbhajan Singh      127
3    Piyush Chawla      126
4     Dwayne Bravo      122

                  bowler  overs  run_given  total_extras  economy  wickets
0            Aaron Finch    7.2         66             1    9.167        1
1        Aavishkar Salvi   25.0        190             6    7.600        7
2       Abhimanyu Mithun   48.0        448            24    9.333        7
3  Abhishek Jhunjhunwala   14.2        126             3    8.873        1
4         Abhishek Nayar   38.3        311             9    8.120        9

In [62]:
bowler_overs[(bowler_overs['economy']>4.0) & (bowler_overs['economy']<7.0)]

                   bowler  overs  run_given  total_extras  economy  wickets
11         Ajinkya Rahane    1.0          5             0    5.000        1
13          Ajit Chandila   39.0        242             0    6.205       11
16            Ali Murtaza   44.0        304             5    6.909        9
26             Andrew Tye   21.0        139             2    6.619       12
29            Anil Kumble  161.0       1027            17    6.379       45
40             Avesh Khan    4.0         23             0    5.750        1
43                B Kumar  330.3       2244            72    6.794      111
50             Ben Stokes   44.0        305            10    6.932       12
62       Charl Langeveldt   26.0        178             9    6.846       13
63         Chetanya Nanda    8.0         55             2    6.875        2
71             Dale Steyn  343.0       2209           101    6.440       92
73         Daniel Vettori  129.5        870             8    6.718       28
82    Dimitri Mascarenhas   51.3        353             2    6.881       19
84            Dirk Nannes  107.5        734            44    6.828       28
86       Dominic Thornely    7.0         38             2    5.429        3
88         Doug Bollinger   96.0        663            24    6.906       37
94          Fidel Edwards   23.7        144             8    6.076        5
95             G H Vihari    6.0         37             1    6.167        1
98          Glenn McGrath   54.0        352             5    6.519       12
99          Graham Napier    4.0         27             0    6.750        1
102       Harbhajan Singh  486.5       3295            70    6.773      127
111            J P Duminy  110.2        766            22    6.951       23
123          Jayant Yadav   30.0        193             3    6.433        4
129           Johan Botha  115.7        781            15    6.750       25
131         John Hastings    9.7         63             3    6.495        3
132           Justin Kemp    7.5         51             2    6.800        3
144         Krunal Pandya   71.2        492            13    6.910       16
148        Lasith Malinga  426.5       2766           135    6.485      154
150        Lee Carseldine    1.0          5             1    5.000        1
152       Lockie Ferguson   13.0         84             9    6.462        3
155         Makhaya Ntini   35.0        238             3    6.800        7
162        Michael Clarke   11.0         67             0    6.091        2
166        Mitchell Starc   96.7        656            32    6.784       34
168       Mohammad Hafeez   10.0         61             3    6.100        2
169         Mohammad Nabi   11.0         58             0    5.273        2
176         Murali Kartik  191.7       1341            32    6.995       31
179     Mustafizur Rahman   63.7        444            11    6.970       17
180  Muttiah Muralitharan  254.7       1642            53    6.447       64
184      Nuwan Kulasekara   17.0        115             5    6.765        5
192      Paul Collingwood   14.8        100             1    6.757        5
205          Rahul Sharma  154.7       1079             7    6.975       40
207         Rahul Tewatia   21.0        137             2    6.524        6
212           Rashid Khan   54.0        352             4    6.519       17
214          Ravi Rampaul   43.7        299            16    6.842       16
215   Ravichandran Ashwin  381.7       2409            69    6.311      100
219  Roelof van der Merwe   73.8        486            12    6.585       21
227    Ryan ten Doeschate   13.0         88             5    6.769        2
229           Sachin Baby    1.7          8             0    4.706        2
230  Sachithra Senanayake   32.0        206             3    6.438        9
240        Shahbaz Nadeem  186.0       1295            21    6.962       37
242       Shakib Al Hasan  153.5       1072            26    6.984       43
245         Shane Harwood   10.0         61             7    6.100        3
249         Shaun Pollock   46.0        297             4    6.457       11
258       Shrikant Mundhe    1.0          5             1    5.000        1
264         Sohail Tanvir   41.5        246            16    5.928       22
272          Sunil Narine  321.8       1999            25    6.212       95
279       Thilan Thushara   22.7        152             8    6.696        8
287       Tyron Henderson    6.0         40             0    6.667        1
299     Washington Sunder   30.0        183             2    6.100        8
300         Wayne Parnell   95.5        651            28    6.817       26

In [63]:
#### plotting the economy of the bowlers. So that during the acution.
#### Segregating the different colors' for very expensive, expensive, economical, very economical
#### Conditions:   very economical <7.0
####               economical >=7.0 and <=10.0
####               expensive >10.0 and <=12.0
####               very expensive >12.0 


Very_Economical = Scatter(x=bowler_overs[bowler_overs['economy']<7.0]['wickets'],
                 y=bowler_overs[bowler_overs['economy']<7.0]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(152, 0, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[bowler_overs['economy']<7.0]['bowler'],
                 name="Very_economical")

Economical = Scatter(x=bowler_overs[(bowler_overs['economy']>=7.0) & (bowler_overs['economy']<=10.0)]['wickets'],
                 y=bowler_overs[(bowler_overs['economy']>=7.0) & (bowler_overs['economy']<=10.0)]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(100, 255, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[(bowler_overs['economy']>=7.0) & (bowler_overs['economy']<=10.0)]['bowler'],
                 name="Economical")


Expensive = Scatter(x=bowler_overs[(bowler_overs['economy']>10.0) & (bowler_overs['economy']<=12.0)]['wickets'],
                 y=bowler_overs[(bowler_overs['economy']>10.0) & (bowler_overs['economy']<=12.0)]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(100, 100, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[(bowler_overs['economy']>10.0) & (bowler_overs['economy']<=12.0)]['bowler'],
                 name="Expensive")

Very_Expensive = Scatter(x=bowler_overs[bowler_overs['economy']>12.0]['wickets'],
                 y=bowler_overs[bowler_overs['economy']>12.0]['economy'],
                 mode="markers",
                 marker=dict(size=9, color='rgba(255, 100, 0, .8)', line=dict(width=1)),
                 text=bowler_overs[bowler_overs['economy']>12.0]['bowler'],
                 name="Very_expensive")

layout = Layout(title="Bowler Economy VS total wickets taken",
                xaxis=dict(title="Total wickets taken in series"),
                yaxis=dict(title="Over all Economy"))

plotly.offline.iplot({
    "data"  :[Very_Economical,Economical,Expensive,Very_Expensive],
    "layout":layout
})

In [64]:
matchs_played=(pa.Series(sum([list(match_data['team1_id']),list(match_data['team2_id'])],[]))).value_counts().reset_index()
matchs_played.columns=['team','matches']

#### Percentage of toss winning based on the matches since 2008.

toss_winners=(match_data['toss_winner'].value_counts()).reset_index()
toss_winners.columns=['team','toss_win_matches']
matchs_played=matchs_played.merge(toss_winners,on='team')
matchs_played['prcnt_toss_winning']= np.round(matchs_played['toss_win_matches']/matchs_played['matches']*100,2)
matchs_played['prcnt_toss_winning']=matchs_played['prcnt_toss_winning'].apply(str)+"% of Toss_winning"

In [65]:
matchs_played.head()

  team  matches  toss_win_matches      prcnt_toss_winning
0   MI      157                85  54.14% of Toss_winning
1  RCB      152                70  46.05% of Toss_winning
2  KXI      148                68  45.95% of Toss_winning
3  KKR      148                78   52.7% of Toss_winning
4   DD      147                72  48.98% of Toss_winning

In [66]:
#### Here we compared How many matches the team played overall and 
#### how many times they own the toss in terms of percentage it ploted.

Toss_winning= Bar(x=matchs_played['team'],
            y=matchs_played['toss_win_matches'],
            marker=dict(color="rgb(158,202,225)"),
            name='Toss_win',
            text=matchs_played['prcnt_toss_winning'])
Matches_played = Bar(x=matchs_played['team'],
             y=matchs_played['matches'],
             marker=dict(color='rgb(100,200,120)'),
             name='Matches_played')

layout = Layout(title="Matches Played VS Toss Winning",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of Matches"))

plotly.offline.iplot({
    "data":[Matches_played,Toss_winning],
    "layout":layout
})

In [67]:
#### What most of the toss winners are choosing the decision to feild or the bat.
#### Lets put a pie chart for the feild and bat decision.

toss_decision=pa.DataFrame((match_data['toss_decision'].value_counts()).reset_index())
toss_decision.columns=['decision','count']
#### appending the percentage for bat and feild.
toss_decision['percentage']=np.round(toss_decision['count']/sum(toss_decision['count'])*100,2)
toss_decision['percentage']=toss_decision['percentage'].apply(str)+"%"

from plotly.graph_objs import Pie

colors=['rgb(128, 0, 255)','rgb(255, 0, 128)']

decision = Pie(labels=toss_decision['decision'],
             values=toss_decision['count'],
             textinfo="label+value",
             marker=dict(colors=colors,
                         line = dict(width=2)),
             textfont=dict(size=20)
            )


plotly.offline.iplot({
    "data":[decision]
})

In [68]:
toss_decision

  decision  count percentage
0    field    363     57.08%
1      bat    273     42.92%

In [69]:
key_team=pa.read_csv("./train/train/key_teams.csv")
#### adding home cities..

cities={"MI":"Mumbai",
             "DD":"Delhi",
              "KKR":"Kolkata",
             "SRH":"Hyderabad",
            "CSK":"Chennai",
             "RR":"Jaipur",
            "RCB":"Bangalore",
            "KXI":"Chandigarh",
            "DC":"Hyderabad",
            "KTK":"Kochi",
            "RPS":"Pune",
           "GL":"Ahmedabad",
           "PW":"Pune"}

In [70]:
key_team['city']=[cities.get(row) for row in key_team['team_id']]

In [71]:
key_team

   team_id                    team_name  Unnamed: 2        city
0       MI               Mumbai Indians         NaN      Mumbai
1       DD             Delhi Daredevils         NaN       Delhi
2      KKR        Kolkata Knight Riders         NaN     Kolkata
3      SRH          Sunrisers Hyderabad         NaN   Hyderabad
4      CSK          Chennai Super Kings         NaN     Chennai
5       RR             Rajasthan Royals         NaN      Jaipur
6      RCB  Royal Challengers Bangalore         NaN   Bangalore
7      KXI              Kings XI Punjab         NaN  Chandigarh
8       DC              Deccan Chargers         NaN   Hyderabad
9      KTK         Kochi Tuskers Kerala         NaN       Kochi
10     RPS      Rising Pune Supergiants         NaN        Pune
11      GL                Gujarat Lions         NaN   Ahmedabad
12      PW                Pune Warriors         NaN        Pune

In [72]:
home_ground_analysis=match_data[['team1_id','team2_id','winner','city']]

In [73]:
home_ground_analysis

    team1_id team2_id winner        city
0        KKR      RCB    KKR   Bangalore
1        CSK      KXI    CSK  Chandigarh
2         RR       DD     DD       Delhi
3         MI      RCB    RCB      Mumbai
4         DC      KKR    KKR     Kolkata
5        KXI       RR     RR      Jaipur
6         DC       DD     DD   Hyderabad
7        CSK       MI    CSK     Chennai
8         DC       RR     RR   Hyderabad
9        KXI       MI    KXI  Chandigarh
10       RCB       RR     RR   Bangalore
11       KKR      CSK    CSK     Chennai
12        MI       DC     DC      Mumbai
13        DD      KXI    KXI  Chandigarh
14       CSK      RCB    CSK   Bangalore
15       KKR       MI     MI     Kolkata
16        DD      RCB     DD       Delhi
17        DC      KXI    KXI   Hyderabad
18        RR      KKR     RR      Jaipur
19       CSK       DD     DD     Chennai
20        DC      RCB    RCB   Hyderabad
21       KXI      KKR    KXI  Chandigarh
22        MI       DD     MI      Mumbai
23       CSK       RR     RR      Jaipur
24       RCB      KXI    KXI   Bangalore
25       CSK       DC     DC     Chennai
26        RR       MI     MI      Mumbai
27        DD      CSK    CSK       Delhi
28       KKR      RCB    KKR     Kolkata
29        DC       RR     RR      Jaipur
..       ...      ...    ...         ...
606      RCB       GL     GL   Bangalore
607       DD      KKR    KKR     Kolkata
608      SRH      KXI    SRH  Chandigarh
609      RPS      RCB    RPS        Pune
610       GL       MI     MI      Rajkot
611       DD      KXI    KXI  Chandigarh
612      SRH      KKR    SRH   Hyderabad
613      RCB       MI     MI      Mumbai
614       GL      RPS    RPS        Pune
615      SRH       DD     DD       Delhi
616      KKR      RPS    RPS     Kolkata
617       GL       DD     DD       Delhi
618      KXI      RCB    KXI   Bangalore
619      RPS      SRH    RPS   Hyderabad
620       MI       DD     MI       Delhi
621      RCB      KKR    KKR   Bangalore
622      KXI       GL     GL  Chandigarh
623       MI      SRH    SRH   Hyderabad
624      KXI      KKR    KXI  Chandigarh
625       GL       DD     DD      Kanpur
626      KXI       MI    KXI      Mumbai
627       DD      RPS     DD       Delhi
628       GL      SRH    SRH      Kanpur
629       MI      KKR     MI     Kolkata
630      KXI      RPS    RPS        Pune
631      RCB       DD    RCB       Delhi
632      RPS       MI    RPS      Mumbai
633      SRH      KKR    KKR   Bangalore
634      KKR       MI     MI   Bangalore
635       MI      RPS     MI   Hyderabad

[636 rows x 4 columns]

In [74]:
home_ground_analysis['home_grnd_team1']=[cities.get(row) for row in home_ground_analysis['team1_id']]

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [75]:
home_ground_analysis['home_grnd_team2']=[cities.get(row) for row in home_ground_analysis['team2_id']]

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [76]:
home_ground_analysis['winner_home_grnd']=[cities.get(row) for row in home_ground_analysis['winner']]

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [77]:
home_ground_analysis['winner_home_grnd']="NaN"

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [78]:
home_ground_analysis['home_grnd']=(home_ground_analysis['winner_home_grnd']==home_ground_analysis['city']).apply(int)

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [79]:
homegrnd_pivot=home_ground_analysis.groupby(['winner','home_grnd'], as_index=False)['home_grnd'].agg({'count':'count'})

In [80]:
####Plotting the analysis of homeground....


trace0 = Bar(x=homegrnd_pivot[homegrnd_pivot['home_grnd']==0]['winner'],
             y=homegrnd_pivot[homegrnd_pivot['home_grnd']==0]['count'],
             marker=dict(color='rgba(100,200,240,0.5)',
                         line=dict(width=2,color='rgba(10,150,150,0.5)')),
             name="Non home ground"
            )

trace1 =Bar(x=homegrnd_pivot[homegrnd_pivot['home_grnd']==1]['winner'],
            y=homegrnd_pivot[homegrnd_pivot['home_grnd']==1]['count'],
            marker=dict(color='rgba(200,202,225,0.9)',
                        line= dict(width=2, color='rgba(100,160,200,0.5)')),
            name="home ground"
           )

layout = Layout(title="Match winnings in Home ground VS Non home ground",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of matches"))

plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})

In [81]:
#### Toss winner choosing the bat or feild decision VS his winning.


toss_winning=match_data[['toss_winner','toss_decision','winner']]

In [82]:
toss_winning['win']= pa.Series((toss_winning['toss_winner']==toss_winning['winner']).apply(int))

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [83]:
toss_winning=toss_winning.groupby(['toss_winner','toss_decision','win'], as_index=False)['win'].agg({'count':'count'})

In [84]:
trace0 = Bar(x=toss_winning[toss_winning['toss_decision']=='field']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='field') & (toss_winning['win']==1)]['count'],
             marker=dict(color='rgb(180,150,200)'),
             name="Field"
            )

trace1 = Bar(x=toss_winning[toss_winning['toss_decision']=='bat']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='bat') & (toss_winning['win']==1)]['count'],
             marker=dict(color='rgb(180,150,100)'),
             name="Bat"
            )
layout = Layout(title="Winning of Toss and winning match VS field or bat",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of matchs Won"))

plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})

In [85]:
trace0 = Bar(x=toss_winning[toss_winning['toss_decision']=='field']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='field') & (toss_winning['win']==0)]['count'],
             marker=dict(color='rgb(180,150,200)'),
             name="Field"
            )

trace1 = Bar(x=toss_winning[toss_winning['toss_decision']=='bat']['toss_winner'],
             y=toss_winning[(toss_winning['toss_decision']=='bat') & (toss_winning['win']==0)]['count'],
             marker=dict(color='rgb(180,150,100)'),
             name="Bat"
            )
layout = Layout(title="Winning of Toss and winning match VS field or bat",
                xaxis=dict(title="Teams"),
                yaxis=dict(title="Number of matchs Won"),
                paper_bgcolor='rgba(0,0,0,0)',
                plot_bgcolor='rgba(0,0,0,0)')

plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})

In [86]:
#### Duckworth-Lewis method application in IPL.
#### This method is applied for calculating the target score for the team batting second when the play interupted by the 
#### whether.


#### Analysis of DL method applied matches.

dl_analysis=match_data[match_data['dl_applied']==1][['team1_id','team2_id','toss_winner','toss_decision','dl_applied','winner']]
dl_analysis['first_bat']='NaN'
dl_analysis['scnd_bat']='NaN'


for i in range(len(dl_analysis)):
    if dl_analysis.iloc[i,3]=='bat':
        dl_analysis.iloc[i,6]=dl_analysis.iloc[i,2]
        if dl_analysis.iloc[i,2]==dl_analysis.iloc[i,0]:
            dl_analysis.iloc[i,7]=dl_analysis.iloc[i,1]
        else:
            dl_analysis.iloc[i,7]=dl_analysis.iloc[i,0]
    else:
        dl_analysis.iloc[i,7]=dl_analysis.iloc[i,2]
        if dl_analysis.iloc[i,2]==dl_analysis.iloc[i,0]:
            dl_analysis.iloc[i,6]=dl_analysis.iloc[i,1]
        else:
            dl_analysis.iloc[i,6]=dl_analysis.iloc[i,0]
            
dl_analysis['first_bat_winner']=(dl_analysis['winner']==dl_analysis['first_bat']).apply(int)

In [87]:
#### plotting the graph


trace0 = Bar(x=(pa.DataFrame(dl_analysis['first_bat'].value_counts()).reset_index())['index'],
             y=(pa.DataFrame(dl_analysis['first_bat'].value_counts()).reset_index())['first_bat'],
             marker=dict(color='rgba(100,200,5,0.5)',
                         line = dict(width=2, color=('rgba(150,200,50,0.9)'))),
             name ="Matches batted first")
trace1 = Bar(x=((dl_analysis[dl_analysis['first_bat_winner']==1]['winner'].value_counts()).reset_index())['index'],
             y=((dl_analysis[dl_analysis['first_bat_winner']==1]['winner'].value_counts()).reset_index())['winner'],
             marker=dict(color='rgba(50,200,25,0.6)',
                         line = dict(width=2, color=('rgba(150,200,50,0.9)'))),
             name="Matches won batting first")


trace2 = Bar(x=(pa.DataFrame(dl_analysis['scnd_bat'].value_counts()).reset_index())['index'],
             y=(pa.DataFrame(dl_analysis['scnd_bat'].value_counts()).reset_index())['scnd_bat'],
             marker=dict(color='rgba(200,100,150,0.5)',
                        line = dict(width=2, color=('rgba(255,100,150,0.9)'))),
             name="Matches batted second")

trace3 = Bar(x=((dl_analysis[dl_analysis['first_bat_winner']==0]['winner'].value_counts()).reset_index())['index'],
             y=((dl_analysis[dl_analysis['first_bat_winner']==0]['winner'].value_counts()).reset_index())['winner'],
             marker=dict(color='rgba(200,5,100,0.5)',
                        line = dict(width=2, color=('rgba(255,100,150,0.9)'))),
             name="Matches won batting second")


layout = Layout(title="Duckworth analysis for the teams playing the bat first and second",
                xaxis=dict(title="Teams played in Duckworth"),
                yaxis=dict(title="Number of Matches"),
                barmode='stack')


plotly.offline.iplot({
    "data":[trace0,trace1,trace2,trace3],
    "layout":layout
})

In [88]:
#### chi square association between toss-decision and winning 


assoc_toss_win_winning=match_data[['toss_winner','toss_decision','winner']]

In [89]:
assoc_toss_win_winning['win']=(assoc_toss_win_winning['toss_winner']==assoc_toss_win_winning['winner']).apply(int)

/home/venugopal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [90]:
assoc_toss_win_winning=assoc_toss_win_winning.groupby(['toss_decision','win'], as_index=False)['win'].agg({'count':'count'})

In [91]:
assoc_toss_win_winning

  toss_decision  win  count
0           bat    0    149
1           bat    1    124
2         field    0    162
3         field    1    201

In [92]:
trace0 = Bar(x=assoc_toss_win_winning[assoc_toss_win_winning['win']==0]['toss_decision'],
             y=assoc_toss_win_winning[assoc_toss_win_winning['win']==0]['count'],
             marker=dict(color='rgb(15,166,200)'),
             name="Winning")

trace1 = Bar(x=assoc_toss_win_winning[assoc_toss_win_winning['win']==1]['toss_decision'],
             y=assoc_toss_win_winning[assoc_toss_win_winning['win']==1]['count'],
             marker=dict(color='rgba(100,5,200,0.6)'),
             name="Lossing")

layout=Layout(title="Association b/n toss winner decision and winning",
              xaxis=dict(title="Toss Decision"),
              yaxis=dict(title="Number of matches"))


plotly.offline.iplot({
    "data":[trace0,trace1],
    "layout":layout
})

In [20]:
#### Chisquare association test

#### pivot table in assoc_toss_win_winning

assoc_toss_win_winning.pivot_table(index='toss_decision',columns='win',fill_value='count')

              count
win               0    1
toss_decision
bat             149  124
field           162  201

In [21]:
#### above we seen the observed values 
#### now calculating the expected values.
#### here chi square is used to calculate the association between the two variables ---->



"""
observed values:

         0       1          row total
bat     149     124           273
  
field   162     201           463

                              
column  311     325           636     over all total
total


"""


"""

Expected values:

i=row
j=column

formula:   E(i,j)  =   (row_total(i)*column_total(j)) / over_all_total
 


           0         1  

bat      133.49     139.50
field    177.50     185.49




chi_square_statistic =  sum(((observed - expected)^2) / expected)

after getting chi square
degree of freedom is calcualted 

(r-1)*(c-1)  -----------> r=number of rows , c = number of columns in cross tabulation.


important note: chi square distrubution is not a symmetric distribution, it is little skewed to right.

degress of freedom = 1


"""

expected_values=[133.49,139.50,226.40,236.59]
observed_values=[[149,124],[162,201]]

from scipy.stats import chi2_contingency

In [22]:
chi2_contingency(observed=observed_values)

(5.7824773620910612,
 0.016186711240844139,
 1,
 array([[ 133.49528302,  139.50471698],
        [ 177.50471698,  185.49528302]]))

In [25]:
#### chisquare = 5.784
#### p-value = 0.016    (p<0.05) so there is significant relation between the winner and toss decision....

In [93]:
ball_by_ball

,match_id,inning,batting_team,bowling_team,over,ball,batsman,batsman_id,non_striker,non_striker_id,bowler,bowler_id,batsman_runs,extra_runs,player_dismissed,player_dismissed_id,dismissal_kind,is_super_over
0,2017_1,1,SRH,RCB,1,1,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
1,2017_1,1,SRH,RCB,1,2,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
2,2017_1,1,SRH,RCB,1,3,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,4,0,NaN,NaN,NaN,0
3,2017_1,1,SRH,RCB,1,4,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
4,2017_1,1,SRH,RCB,1,5,David Warner,207,Shikhar Dhawan,57,Tymal Mills,621,0,2,NaN,NaN,NaN,0
5,2017_1,1,SRH,RCB,1,6,Shikhar Dhawan,57,David Warner,207,Tymal Mills,621,0,0,NaN,NaN,NaN,0
6,2017_1,1,SRH,RCB,1,7,Shikhar Dhawan,57,David Warner,207,Tymal Mills,621,0,1,NaN,NaN,NaN,0
7,2017_1,1,SRH,RCB,2,1,Shikhar Dhawan,57,David Warner,207,Aniket Choudhary,480,1,0,NaN,NaN,NaN,0
8,2017_1,1,SRH,RCB,2,2,David Warner,207,Shikhar Dhawan,57,Aniket Choudhary,480,4,0,NaN,NaN,NaN,0
9,2017_1,1,SRH,RCB,2,3,David Warner,207,Shikhar Dhawan,57,Aniket Choudhary,480,0,1,NaN,NaN,NaN,0
10,2017_1,1,SRH,RCB,2,4,David Warner,207,Shikhar Dhawan,57,Aniket Choudhary,480,6,0,NaN,NaN,NaN,0
11,2017_1,1,SRH,RCB,2,5,David Warner,207,Shikhar Dhawan,57,Aniket Choudhary,480,0,0,David Warner,207.0,caught,0
12,2017_1,1,SRH,RCB,2,6,Moises Henriques,212,Shikhar Dhawan,57,Aniket Choudhary,480,0,0,NaN,NaN,NaN,0
13,2017_1,1,SRH,RCB,2,7,Moises Henriques,212,Shikhar Dhawan,57,Aniket Choudhary,480,4,0,NaN,NaN,NaN,0
14,2017_1,1,SRH,RCB,3,1,Shikhar Dhawan,57,Moises Henriques,212,Tymal Mills,621,1,0,NaN,NaN,NaN,0
15,2017_1,1,SRH,RCB,3,2,Moises Henriques,212,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
16,2017_1,1,SRH,RCB,3,3,Moises Henriques,212,Shikhar Dhawan,57,Tymal Mills,621,0,0,NaN,NaN,NaN,0
17,2017_1,1,SRH,RCB,3,4,Moises Henriques,212,Shikhar Dhawan,57,Tymal Mills,621,3,0,NaN,NaN,NaN,0
18,2017_1,1,SRH,RCB,3,5,Shikhar Dhawan,57,Moises Henriques,212,Tymal Mills,621,1,0,NaN,NaN,NaN,0
19,2017_1,1,SRH,RCB,3,6,Moises Henriques,212,Shikhar Dhawan,57,Tymal Mills,621,1,0,NaN,NaN,NaN,0
20,2017_1,1,SRH,RCB,4,1,Moises Henriques,212,Shikhar Dhawan,57,Yuzvendra Chahal,682,0,0,NaN,NaN,NaN,0
21,2017_1,1,SRH,RCB,4,2,Moises Henriques,212,Shikhar Dhawan,57,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN,0
22,2017_1,1,SRH,RCB,4,3,Shikhar Dhawan,57,Moises Henriques,212,Yuzvendra Chahal,682,0,0,NaN,NaN,NaN,0
23,2017_1,1,SRH,RCB,4,4,Shikhar Dhawan,57,Moises Henriques,212,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN,0
24,2017_1,1,SRH,RCB,4,5,Moises Henriques,212,Shikhar Dhawan,57,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN,0
25,2017_1,1,SRH,RCB,4,6,Shikhar Dhawan,57,Moises Henriques,212,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN,0
26,2017_1,1,SRH,RCB,5,1,Shikhar Dhawan,57,Moises Henriques,212,Sreenath Aravind,237,1,0,NaN,NaN,NaN,0
27,2017_1,1,SRH,RCB,5,2,Moises Henriques,212,Shikhar Dhawan,57,Sreenath Aravind,237,1,0,NaN,NaN,NaN,0
28,2017_1,1,SRH,RCB,5,3,Shikhar Dhawan,57,Moises Henriques,212,Sreenath Aravind,237,1,0,NaN,NaN,NaN,0
29,2017_1,1,SRH,RCB,5,4,Moises Henriques,212,Shikhar Dhawan,57,Sreenath Aravind,237,2,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150430,2016_60,2,RCB,SRH,16,1,KL Rahul,668,Shane Watson,175,Ben Cutting,526,1,0,NaN,NaN,NaN,0
150431,2016_60,2,RCB,SRH,16,2,Shane Watson,175,KL Rahul,668,Ben Cutting,526,1,0,NaN,NaN,NaN,0
150432,2016_60,2,RCB,SRH,16,3,KL Rahul,668,Shane Watson,175,Ben Cutting,526,0,0,KL Rahul,668.0,bowled,0
150433,2016_60,2,RCB,SRH,16,4,Sachin Baby,500,Shane Watson,175,Ben Cutting,526,0,0,NaN,NaN,NaN,0
150434,2016_60,2,RCB,SRH,16,5,Sachin Baby,500,Shane Watson,175,Ben Cutting,526,1,0,NaN,NaN,NaN,0
150435,2016_60,2,RCB,SRH,16,6,Shane Watson,175,Sachin Baby,500,Ben Cutting,526,1,0,NaN,NaN,NaN,0
150436,2016_60,2,RCB,SRH,17,1,Shane Watson,175,Sachin Baby,500,Mustafizur Rahman,593,0,0,NaN,NaN,NaN,0
150437,2016_60,2,RCB,SRH,17,2,Shane Watson,175,Sachin Baby,500,Mustafizur Rahman,593,2,0,NaN,NaN,NaN,0
150438,2016_60,2,RCB,SRH,17,3,Shane Watson,175,Sachin Baby,500,Mustafizur Rahman,593,0,0,Shane Watson,175.0,caught,0
150439,2016_60,2,RCB,SRH,17,4,Sachin Baby,500,Stuart Binny,411,Mustafizur Rahman,593,1,0,NaN,NaN,NaN,0
150440,2016_60,2,RCB,SRH,17,5,Stuart Binny,411,Sachin Baby,500,Mustafizur Rahman,593,6,0,NaN,NaN,NaN,0
150441,2016_60,2,RCB,SRH,17,6,Stuart Binny,411,Sachin Baby,500,Mustafizur Rahman,593,1,0,NaN,NaN,NaN,0
150442,2016_60,2,RCB,SRH,18,1,Stuart Binny,411,Sachin Baby,500,B Kumar,691,0,0,NaN,NaN,NaN,0
150443,2016_60,2,RCB,SRH,18,2,Stuart Binny,411,Sachin Baby,500,B Kumar,691,1,0,NaN,NaN,NaN,0
150444,2016_60,2,RCB,SRH,18,3,Sachin Baby,500,Stuart Binny,411,B Kumar,691,1,0,NaN,NaN,NaN,0
150445,2016_60,2,RCB,SRH,18,4,Stuart Binny,411,Sachin Baby,500,B Kumar,691,0,0,NaN,NaN,NaN,0
150446,2016_60,2,RCB,SRH,18,5,Stuart Binny,411,Sachin Baby,500,B Kumar,691,0,1,NaN,NaN,NaN,0
150447,2016_60,2,RCB,SRH,18,6,Sachin Baby,500,Stuart Binny,411,B Kumar,691,4,0,NaN,NaN,NaN,0
150448,2016_60,2,RCB,SRH,19,1,Stuart Binny,411,Sachin Baby,500,Mustafizur Rahman,593,1,0,Stuart Binny,411.0,run out,0
150449,2016_60,2,RCB,SRH,19,2,Chris Jordan,632,Sachin Baby,500,Mustafizur Rahman,593,2,0,NaN,NaN,NaN,0
150450,2016_60,2,RCB,SRH,19,3,Chris Jordan,632,Sachin Baby,500,Mustafizur Rahman,593,0,0,NaN,NaN,NaN,0
150451,2016_60,2,RCB,SRH,19,4,Chris Jordan,632,Sachin Baby,500,Mustafizur Rahman,593,0,1,NaN,NaN,NaN,0
150452,2016_60,2,RCB,SRH,19,5,Sachin Baby,500,Chris Jordan,632,Mustafizur Rahman,593,2,0,NaN,NaN,NaN,0
150453,2016_60,2,RCB,SRH,19,6,Sachin Baby,500,Chris Jordan,632,Mustafizur Rahman,593,6,0,NaN,NaN,NaN,0
150454,2016_60,2,RCB,SRH,20,1,Chris Jordan,632,Sachin Baby,500,B Kumar,691,1,0,NaN,NaN,NaN,0
150455,2016_60,2,RCB,SRH,20,2,Sachin Baby,500,Chris Jordan,632,B Kumar,691,2,0,NaN,NaN,NaN,0
150456,2016_60,2,RCB,SRH,20,3,Sachin Baby,500,Chris Jordan,632,B Kumar,691,0,0,Chris Jordan,632.0,run out,0
150457,2016_60,2,RCB,SRH,20,4,Iqbal Abdulla,70,Sachin Baby,500,B Kumar,691,0,1,NaN,NaN,NaN,0
150458,2016_60,2,RCB,SRH,20,5,Sachin Baby,500,Iqbal Abdulla,70,B Kumar,691,1,0,NaN,NaN,NaN,0
150459,2016_60,2,RCB,SRH,20,6,Iqbal Abdulla,70,Sachin Baby,500,B Kumar,691,4,0,NaN,NaN,NaN,0

In [101]:
team_scores=ball_by_ball[(ball_by_ball['inning']==1) | (ball_by_ball['inning']==2)][['match_id','batting_team','inning','batsman_runs','extra_runs']]

In [102]:
team_scores

       match_id batting_team  inning  batsman_runs  extra_runs
0        2017_1          SRH       1             0           0
1        2017_1          SRH       1             0           0
2        2017_1          SRH       1             4           0
3        2017_1          SRH       1             0           0
4        2017_1          SRH       1             0           2
5        2017_1          SRH       1             0           0
6        2017_1          SRH       1             0           1
7        2017_1          SRH       1             1           0
8        2017_1          SRH       1             4           0
9        2017_1          SRH       1             0           1
10       2017_1          SRH       1             6           0
11       2017_1          SRH       1             0           0
12       2017_1          SRH       1             0           0
13       2017_1          SRH       1             4           0
14       2017_1          SRH       1             1           0
15       2017_1          SRH       1             0           0
16       2017_1          SRH       1             0           0
17       2017_1          SRH       1             3           0
18       2017_1          SRH       1             1           0
19       2017_1          SRH       1             1           0
20       2017_1          SRH       1             0           0
21       2017_1          SRH       1             1           0
22       2017_1          SRH       1             0           0
23       2017_1          SRH       1             1           0
24       2017_1          SRH       1             1           0
25       2017_1          SRH       1             1           0
26       2017_1          SRH       1             1           0
27       2017_1          SRH       1             1           0
28       2017_1          SRH       1             1           0
29       2017_1          SRH       1             2           0
...         ...          ...     ...           ...         ...
150430  2016_60          RCB       2             1           0
150431  2016_60          RCB       2             1           0
150432  2016_60          RCB       2             0           0
150433  2016_60          RCB       2             0           0
150434  2016_60          RCB       2             1           0
150435  2016_60          RCB       2             1           0
150436  2016_60          RCB       2             0           0
150437  2016_60          RCB       2             2           0
150438  2016_60          RCB       2             0           0
150439  2016_60          RCB       2             1           0
150440  2016_60          RCB       2             6           0
150441  2016_60          RCB       2             1           0
150442  2016_60          RCB       2             0           0
150443  2016_60          RCB       2             1           0
150444  2016_60          RCB       2             1           0
150445  2016_60          RCB       2             0           0
150446  2016_60          RCB       2             0           1
150447  2016_60          RCB       2             4           0
150448  2016_60          RCB       2             1           0
150449  2016_60          RCB       2             2           0
150450  2016_60          RCB       2             0           0
150451  2016_60          RCB       2             0           1
150452  2016_60          RCB       2             2           0
150453  2016_60          RCB       2             6           0
150454  2016_60          RCB       2             1           0
150455  2016_60          RCB       2             2           0
150456  2016_60          RCB       2             0           0
150457  2016_60          RCB       2             0           1
150458  2016_60          RCB       2             1           0
150459  2016_60          RCB       2             4           0

[150379 rows x 5 columns]

In [104]:
team_scores=team_scores.groupby(['match_id','batting_team','inning'],as_index=False)['batsman_runs','extra_runs'].agg({'batsman_runs':'sum','extra_runs':'sum'})

In [105]:
team_scores['total_score']=team_scores['batsman_runs']+team_scores['extra_runs']

In [120]:
team_scores_1st_inn=team_scores[team_scores['inning']==1][['batting_team','total_score']]
team_scores_2st_inn=team_scores[team_scores['inning']==2][['batting_team','total_score']]

In [110]:
from plotly.graph_objs import Box

In [112]:
team_scores['batting_team'].unique()

array(['KKR', 'RCB', 'KXI', 'MI', 'RR', 'CSK', 'DC', 'DD', 'KTK', 'PW',
       'SRH', 'RPS', 'GL'], dtype=object)

In [121]:
trace0 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='KKR']['total_score'], name='KKR')
trace1 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='RCB']['total_score'], name='RCB')
trace2 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='KXI']['total_score'], name='KXI')
trace3 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='MI']['total_score'], name='MI')
trace4 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='RR']['total_score'], name='RR')
trace5 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='CSK']['total_score'], name='CSK')
trace6 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='DC']['total_score'], name='DC')
trace7 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='DD']['total_score'], name='DD')
trace8 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='KTK']['total_score'], name='KTK')
trace9 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='PW']['total_score'], name='PW')
trace10 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='SRH']['total_score'], name='SRH')
trace11 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='RPS']['total_score'], name='RPS')
trace12 = Box(y=team_scores_1st_inn[team_scores_1st_inn['batting_team']=='GL']['total_score'], name='GL')


plotly.offline.iplot({
    "data":[trace0,trace1,trace2,trace3,trace4,trace5,trace6,trace7,trace8,trace9,trace10,trace11,trace12]
})

In [122]:
trace0 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='KKR']['total_score'], name='KKR')
trace1 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='RCB']['total_score'], name='RCB')
trace2 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='KXI']['total_score'], name='KXI')
trace3 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='MI']['total_score'], name='MI')
trace4 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='RR']['total_score'], name='RR')
trace5 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='CSK']['total_score'], name='CSK')
trace6 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='DC']['total_score'], name='DC')
trace7 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='DD']['total_score'], name='DD')
trace8 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='KTK']['total_score'], name='KTK')
trace9 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='PW']['total_score'], name='PW')
trace10 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='SRH']['total_score'], name='SRH')
trace11 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='RPS']['total_score'], name='RPS')
trace12 = Box(y=team_scores_2st_inn[team_scores_2st_inn['batting_team']=='GL']['total_score'], name='GL')


plotly.offline.iplot({
    "data":[trace0,trace1,trace2,trace3,trace4,trace5,trace6,trace7,trace8,trace9,trace10,trace11,trace12]
})

In [129]:
### sixes analysis

boundary_analysis=ball_by_ball[(ball_by_ball['inning']==1) | (ball_by_ball['inning']==2)][['match_id','batting_team','inning','batsman','batsman_runs','extra_runs']]

In [142]:
sixes=boundary_analysis[boundary_analysis['batsman_runs']==6][['match_id','batting_team','inning','batsman','batsman_runs','extra_runs']]

In [143]:
#### Top 5 six hitter in IPL


sixes=sixes.groupby(['batsman','batsman_runs'], as_index=False)['batsman_runs'].agg({'sixes':'count'})

In [145]:
### total_matches 

total_matches=boundary_analysis.groupby(['batsman'], as_index=False)['match_id'].count()

In [147]:
sixes=sixes.merge(total_matches, on='batsman')

In [148]:
sixes

                     batsman  batsman_runs  sixes  match_id
0             AB De Villiers             6    156      2398
1                Aaron Finch             6     59      1266
2           Abhimanyu Mithun             6      1        26
3      Abhishek Jhunjhunwala             6      5       218
4             Abhishek Nayar             6     20       588
5              Abhishek Raut             6      7       172
6                 Abu Nechim             6      1        27
7             Adam Gilchrist             6     92      1555
8                 Adam Voges             6      3       143
9                Aditya Dole             6      1        23
10               Aditya Tare             6     11       285
11             Adrian Barath             6      1        43
12            Aiden Blizzard             6      2        91
13            Ajinkya Rahane             6     60      2602
14              Ajit Agarkar             6      5       160
15             Akshath Reddy             6      2       167
16              Albie Morkel             6     55       711
17            Alfonso Thomas             6      1        19
18             Ambati Rayudu             6     79      1964
19               Amit Mishra             6      5       382
20                Amit Yadav             6      2        40
21             Andre Russell             6     37       350
22           Andrew Flintoff             6      2        57
23           Andrew McDonald             6      4       103
24            Andrew Symonds             6     41       781
25                Andrew Tye             6      3        30
26            Angelo Mathews             6     29       599
27          Aniket Choudhary             6      1        20
28             Anirudh Singh             6      1        69
29              Ankit Sharma             6      4        69
..                       ...           ...    ...       ...
271           Thisara Perera             6     26       324
272     Tillakaratne Dilshan             6     24      1047
273              Tim Southee             6      3        36
274       Tirumalsetti Suman             6     26       587
275              Travis Birt             6      2        59
276              Travis Head             6      8       151
277              Tymal Mills             6      1        11
278          Tyron Henderson             6      1        16
279                 Umar Gul             6      5        19
280              Umesh Yadav             6      3        95
281             Unmukt Chand             6      9       314
282            Usman Khawaja             6      3       105
283               VVS Laxman             6      5       271
284              Varun Aaron             6      2        56
285            Venugopal Rao             6     37       865
286  Vidyut Sivaramakrishnan             6      3       115
287            Vijay Shankar             6      1        77
288                Vijay Zol             6      1        26
289              Vinay Kumar             6      9       285
290              Virat Kohli             6    160      3492
291          Virender Sehwag             6    106      1833
292             Vishnu Vinod             6      1        26
293             Wasim Jaffer             6      3       129
294            Wayne Parnell             6      1        80
295          Wriddhiman Saha             6     57      1219
296             Yogesh Nagar             6      9       271
297          Yogesh Takawale             6      3       183
298             Yusuf Pathan             6    147      2072
299             Yuvraj Singh             6    141      2048
300              Zaheer Khan             6      2       141

[301 rows x 4 columns]

In [159]:
#### top 10 six beaten batsman


trace0 = Scatter(x=sixes['match_id'],
                 y=sixes['sixes'],
                 mode="markers",
                 marker=dict(color='rgba(40,50,20,0.6)', size=10),
                 text=sixes['batsman'])

layout = Layout(title="Number matches played vs Sixes",
                xaxis=dict(title="Number of matches played"),
                yaxis=dict(title="Number of sixes"))

plotly.offline.iplot({
    "data":[trace0],
    'layout':layout
})

In [161]:
### what is the trend of the sixes based on the years.



sixes_trend=ball_by_ball[(ball_by_ball['inning']==1) | (ball_by_ball['inning']==2)][['match_id','batting_team','inning','batsman','batsman_runs','extra_runs']]

In [173]:
sixes_trend['season']=[row.split("_")[0] for row in sixes_trend['match_id']]

In [178]:
six=sixes_trend[sixes_trend['batsman_runs']==6].groupby(['season'], as_index=False)['batsman_runs'].count()
four=sixes_trend[sixes_trend['batsman_runs']==4].groupby(['season'], as_index=False)['batsman_runs'].count()
ones=sixes_trend[sixes_trend['batsman_runs']==1].groupby(['season'], as_index=False)['batsman_runs'].count()
twos=sixes_trend[sixes_trend['batsman_runs']==2].groupby(['season'], as_index=False)['batsman_runs'].count()
threes=sixes_trend[sixes_trend['batsman_runs']==3].groupby(['season'], as_index=False)['batsman_runs'].count()

In [181]:
trace0 = Scatter(x=six['season'],
              y=six['batsman_runs'],
              mode="lines+markers",
              name="Sixes")

trace1 = Scatter(x=four['season'],
              y=four['batsman_runs'],
              mode="lines+markers",
              name="Fours")
trace2 = Scatter(x=ones['season'],
              y=ones['batsman_runs'],
              mode="lines+markers",
              name="ones")
trace3 = Scatter(x=twos['season'],
              y=twos['batsman_runs'],
              mode="lines+markers",
              name="Twos")
trace4 = Scatter(x=threes['season'],
              y=threes['batsman_runs'],
              mode="lines+markers",
              name="Threes")



layout=Layout(title="Trend line for ones,twos, threes, fours, sixes",
              xaxis=dict(title="seasons"),
              yaxis=dict(title="Trends"))


plotly.offline.iplot({
    "data":[trace0,trace1,trace2,trace3,trace4],
    "layout":layout
})

In [ ]:
#### trend lines of sixes