In [1]:
####Visualizations
#### Importing dependencies 
import numpy as np
import pandas as pa
import seaborn as se
import matplotlib.pyplot as plt
from IPython.display import HTML

In [2]:
ball_by_ball = pa.read_csv("./train/train/ball_by_ball_data.csv")
match_data = pa.read_csv("./train/train/match_data.csv")
player_roster = pa.read_csv("./train/train/player_rosters.csv")
key_teams = pa.read_csv("./train/train/key_teams.csv")
matchs_2018=pa.read_csv("./test/test/matches_2018.csv")
player_prediction_2018=pa.read_csv("./test/test/player_predictions.csv")

In [5]:
filter_data=ball_by_ball[['match_id','inning','batting_team','bowling_team','over','bowler','bowler_id','batsman_runs','extra_runs','player_dismissed','player_dismissed_id','dismissal_kind']]

In [9]:
filter_data_1st_inn = filter_data[filter_data['inning']==1]
filter_data_2nd_inn = filter_data[filter_data['inning']==2]

In [10]:
filter_data_1st_inn[]

,match_id,inning,batting_team,bowling_team,over,bowler,bowler_id,batsman_runs,extra_runs,player_dismissed,player_dismissed_id,dismissal_kind
0,2017_1,1,SRH,RCB,1,Tymal Mills,621,0,0,NaN,NaN,NaN
1,2017_1,1,SRH,RCB,1,Tymal Mills,621,0,0,NaN,NaN,NaN
2,2017_1,1,SRH,RCB,1,Tymal Mills,621,4,0,NaN,NaN,NaN
3,2017_1,1,SRH,RCB,1,Tymal Mills,621,0,0,NaN,NaN,NaN
4,2017_1,1,SRH,RCB,1,Tymal Mills,621,0,2,NaN,NaN,NaN
5,2017_1,1,SRH,RCB,1,Tymal Mills,621,0,0,NaN,NaN,NaN
6,2017_1,1,SRH,RCB,1,Tymal Mills,621,0,1,NaN,NaN,NaN
7,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,1,0,NaN,NaN,NaN
8,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,4,0,NaN,NaN,NaN
9,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,0,1,NaN,NaN,NaN
10,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,6,0,NaN,NaN,NaN
11,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,0,0,David Warner,207.0,caught
12,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,0,0,NaN,NaN,NaN
13,2017_1,1,SRH,RCB,2,Aniket Choudhary,480,4,0,NaN,NaN,NaN
14,2017_1,1,SRH,RCB,3,Tymal Mills,621,1,0,NaN,NaN,NaN
15,2017_1,1,SRH,RCB,3,Tymal Mills,621,0,0,NaN,NaN,NaN
16,2017_1,1,SRH,RCB,3,Tymal Mills,621,0,0,NaN,NaN,NaN
17,2017_1,1,SRH,RCB,3,Tymal Mills,621,3,0,NaN,NaN,NaN
18,2017_1,1,SRH,RCB,3,Tymal Mills,621,1,0,NaN,NaN,NaN
19,2017_1,1,SRH,RCB,3,Tymal Mills,621,1,0,NaN,NaN,NaN
20,2017_1,1,SRH,RCB,4,Yuzvendra Chahal,682,0,0,NaN,NaN,NaN
21,2017_1,1,SRH,RCB,4,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN
22,2017_1,1,SRH,RCB,4,Yuzvendra Chahal,682,0,0,NaN,NaN,NaN
23,2017_1,1,SRH,RCB,4,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN
24,2017_1,1,SRH,RCB,4,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN
25,2017_1,1,SRH,RCB,4,Yuzvendra Chahal,682,1,0,NaN,NaN,NaN
26,2017_1,1,SRH,RCB,5,Sreenath Aravind,237,1,0,NaN,NaN,NaN
27,2017_1,1,SRH,RCB,5,Sreenath Aravind,237,1,0,NaN,NaN,NaN
28,2017_1,1,SRH,RCB,5,Sreenath Aravind,237,1,0,NaN,NaN,NaN
29,2017_1,1,SRH,RCB,5,Sreenath Aravind,237,2,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
150306,2016_60,1,SRH,RCB,16,Sreenath Aravind,237,1,0,NaN,NaN,NaN
150307,2016_60,1,SRH,RCB,16,Sreenath Aravind,237,0,0,Deepak Hooda,529.0,caught
150308,2016_60,1,SRH,RCB,17,Chris Jordan,632,0,1,NaN,NaN,NaN
150309,2016_60,1,SRH,RCB,17,Chris Jordan,632,0,0,Yuvraj Singh,88.0,caught
150310,2016_60,1,SRH,RCB,17,Chris Jordan,632,4,0,NaN,NaN,NaN
150311,2016_60,1,SRH,RCB,17,Chris Jordan,632,1,0,NaN,NaN,NaN
150312,2016_60,1,SRH,RCB,17,Chris Jordan,632,0,1,NaN,NaN,NaN
150313,2016_60,1,SRH,RCB,17,Chris Jordan,632,0,0,NaN,NaN,NaN
150314,2016_60,1,SRH,RCB,17,Chris Jordan,632,2,0,NaN,NaN,NaN
150315,2016_60,1,SRH,RCB,18,Shane Watson,175,0,1,NaN,NaN,NaN
150316,2016_60,1,SRH,RCB,18,Shane Watson,175,0,1,NaN,NaN,NaN
150317,2016_60,1,SRH,RCB,18,Shane Watson,175,0,0,Naman Ojha,271.0,run out
150318,2016_60,1,SRH,RCB,18,Shane Watson,175,0,0,NaN,NaN,NaN
150319,2016_60,1,SRH,RCB,18,Shane Watson,175,6,0,NaN,NaN,NaN
150320,2016_60,1,SRH,RCB,18,Shane Watson,175,0,0,NaN,NaN,NaN
150321,2016_60,1,SRH,RCB,18,Shane Watson,175,4,0,NaN,NaN,NaN
150322,2016_60,1,SRH,RCB,18,Shane Watson,175,0,0,NaN,NaN,NaN
150323,2016_60,1,SRH,RCB,19,Chris Jordan,632,1,0,NaN,NaN,NaN
150324,2016_60,1,SRH,RCB,19,Chris Jordan,632,1,0,NaN,NaN,NaN
150325,2016_60,1,SRH,RCB,19,Chris Jordan,632,4,0,NaN,NaN,NaN
150326,2016_60,1,SRH,RCB,19,Chris Jordan,632,0,0,Bipul Sharma,305.0,caught
150327,2016_60,1,SRH,RCB,19,Chris Jordan,632,0,5,NaN,NaN,NaN
150328,2016_60,1,SRH,RCB,19,Chris Jordan,632,4,0,NaN,NaN,NaN
150329,2016_60,1,SRH,RCB,19,Chris Jordan,632,1,0,NaN,NaN,NaN
150330,2016_60,1,SRH,RCB,20,Shane Watson,175,4,0,NaN,NaN,NaN
150331,2016_60,1,SRH,RCB,20,Shane Watson,175,6,0,NaN,NaN,NaN
150332,2016_60,1,SRH,RCB,20,Shane Watson,175,6,0,NaN,NaN,NaN
150333,2016_60,1,SRH,RCB,20,Shane Watson,175,1,0,NaN,NaN,NaN
150334,2016_60,1,SRH,RCB,20,Shane Watson,175,1,0,NaN,NaN,NaN
150335,2016_60,1,SRH,RCB,20,Shane Watson,175,6,0,NaN,NaN,NaN